import * as fs from "node:fs";
import * as path from "node:path";
import { readArtifact } from "./readArtifact.ts";
import { classify } from "./classifyArtifact.ts";
import { esc, htmlShell, statusBadge, typeBadge } from "./helpers/render.ts";
import { OUTPUT_DIR } from "./output.ts";

interface ArtifactEntry {
  title: string;
  type: "design-doc" | "handoff" | "plan" | "generic";
  status?: string;
  mdPath: string;
  htmlPath: string;
  mtime: number;
}

function isArtifactMd(name: string): boolean {
  if (!name.endsWith(".md")) return false;
  if (name.startsWith(".")) return false;
  return true;
}

function collectArtifacts(dir: string): ArtifactEntry[] {
  const entries: ArtifactEntry[] = [];
  let names: string[];
  try {
    names = fs.readdirSync(dir);
  } catch {
    return entries;
  }
  for (const name of names) {
    if (!isArtifactMd(name)) continue;
    const mdPath = path.join(dir, name);
    let stat: fs.Stats;
    try {
      stat = fs.statSync(mdPath);
    } catch {
      continue;
    }
    if (!stat.isFile()) continue;

    let artifact;
    try {
      artifact = readArtifact(mdPath);
    } catch {
      // readArtifact die()s on parse error — for dashboard purposes,
      // wrap in try/catch and skip broken files silently.
      continue;
    }

    let classified;
    try {
      classified = classify(artifact);
    } catch {
      continue;
    }

    let title = name.replace(/\.md$/, "");
    let typeKind: ArtifactEntry["type"] = "generic";
    let status: string | undefined;

    if (classified.kind === "design-doc") {
      title = classified.frontmatter.title;
      typeKind = "design-doc";
      status = classified.frontmatter.status;
    } else if (classified.kind === "handoff") {
      title =
        classified.frontmatter.active_task ??
        classified.frontmatter.next_step.slice(0, 60);
      typeKind = "handoff";
      status = classified.frontmatter.status;
    } else if (classified.kind === "plan") {
      title = classified.frontmatter.title;
      typeKind = "plan";
      status = classified.frontmatter.status;
    } else {
      const fm = classified.frontmatter;
      if (typeof fm.title === "string") title = fm.title;
      if (typeof fm.status === "string") status = fm.status;
    }

    const htmlPath = path.join(OUTPUT_DIR, `${path.basename(name, ".md")}.html`);
    entries.push({
      title,
      type: typeKind,
      status,
      mdPath: name, // relative to the index location's parent
      htmlPath, // relative to the index location's parent
      mtime: stat.mtimeMs,
    });
  }
  entries.sort((a, b) => b.mtime - a.mtime);
  return entries;
}

function formatDate(ms: number): string {
  return new Date(ms).toISOString().slice(0, 10);
}

export function renderDashboard(dir: string, cssHref: string): string {
  const absDir = path.resolve(dir);
  const projectName = path.basename(absDir);
  const entries = collectArtifacts(absDir);

  const indexPath = path.join(absDir, OUTPUT_DIR, "index.html");
  // mdPath/htmlPath in entries are relative to absDir; index lives in absDir/.superpowers-html/
  // so links need ../<mdPath> for source and <basename>.html for companion (same dir).
  // Companion is in same dir as index: just basename of htmlPath.

  const list =
    entries.length === 0
      ? `<p class="dashboard-empty">No companions yet. Run <code>htmlify &lt;file.md&gt;</code> to create one.</p>`
      : `<ul class="artifact-list">
${entries
  .map((e) => {
    const companionBase = path.basename(e.htmlPath);
    const sourceMdRel = `../${e.mdPath}`;
    return `<li class="artifact">
  <span class="artifact-date">${esc(formatDate(e.mtime))}</span>
  <h2 class="artifact-title"><a href="${esc(companionBase)}">${esc(e.title)}</a></h2>
  <div class="artifact-badges">${typeBadge(e.type)}${statusBadge(e.status)}</div>
  <p class="artifact-source"><a href="${esc(sourceMdRel)}">source MD</a></p>
</li>`;
  })
  .join("\n")}
</ul>`;

  const body = `<h1>${esc(projectName)}</h1>
<p class="dashboard-meta">${entries.length} artifact${entries.length === 1 ? "" : "s"} · sorted by recency</p>
<main>${list}</main>
<footer class="companion-footer">
  <p class="footer-meta">Generated by superpowers-gstack · htmlify dashboard</p>
</footer>`;

  return htmlShell({
    title: `${projectName} — htmlify dashboard`,
    cssHref,
    bodyClass: "dashboard",
    body,
  });
}

export function writeDashboard(dir: string, cssHref: string): string {
  const absDir = path.resolve(dir);
  const outDir = path.join(absDir, OUTPUT_DIR);
  try {
    fs.mkdirSync(outDir, { recursive: true });
  } catch (err: any) {
    process.stderr.write(
      `Warning: cannot create dashboard output dir ${outDir}: ${err?.message ?? err}\n`
    );
    return "";
  }
  const html = renderDashboard(absDir, cssHref);
  const indexPath = path.join(outDir, "index.html");
  fs.writeFileSync(indexPath, html);
  return indexPath;
}
