#!/usr/bin/env bash
# Auto-generated by /e2e-scaffold
# Runs the committed XCUITest suite and prints one Claude-readable JSON summary:
#   {total, passed, failed, skipped, executed, executor, xcresult, results[]}
# Requires Xcode 16+ for the JSON xcresulttool format; older Xcode falls back to plaintext.
#
# Exit codes: 0 = every executed test passed; 2 = could not run (setup error, invalid
# pin, rig fault); any other non-zero = a failed run. That status is xcodebuild's own,
# passed through unchanged, so it is typically 65 — NOT 1. Check `-ne 0`, never `-eq 1`.
#
# Layering: this script CHOOSES the executor; `vm-e2e` OWNS the lease and the guest.
# It only READS `.gstack/e2e-executor` — /setup-routing and /adapt write that pin.

set -uo pipefail

# Run from the project root regardless of where the caller stood. Every path below is
# relative to it — `.gstack/e2e-executor` above all. Read from a subdirectory the pin is
# simply not found, and an INVALID pin would degrade to a silent host run: the one
# outcome the pin exists to prevent.
cd "$(cd "$(dirname "$0")/.." && pwd)" || { echo "cannot resolve project root" >&2; exit 2; }

# Single-quoted on purpose: the scaffold validates these against ^[A-Za-z0-9_.-]+( [A-Za-z0-9_.-]+)*$
# before substituting, and single quotes keep a name that slipped through from ever
# being expanded — a scheme called `$(x)` is a file name, not a command.
SCHEME='<SCHEME>'
PLATFORM='<PLATFORM>'          # macos | ios
TEST_TARGET='<TEST_TARGET>'    # <App>UITests, or <App>macOSUITests / <App>iOSUITests on multiplatform
case "$SCHEME$TEST_TARGET" in *[!A-Za-z0-9_.\ -]*) echo "refusing: scheme/target name carries shell-significant characters" >&2; exit 2 ;; esac

# --- Executor pin ---------------------------------------------------------------
# host | vm; absence means host. Only those two exact strings are valid: a typo that
# silently ran on the host is the failure this pin exists to prevent, because the run
# still looks fine afterwards.
EXECUTOR=host
if [ -f .gstack/e2e-executor ]; then
  # `$( )` strips exactly the trailing newline the generators write and nothing else,
  # so the case below sees the whole file: `vm ` keeps its space, `v m` its gap, and a
  # second line stays attached. Every one of those is then BLOCKED. Do not normalise
  # first (`tr -d '[:space:]'`, `head -1 | sed`): that launders junk into a legal value
  # instead of validating it.
  EXECUTOR=$(cat .gstack/e2e-executor)
  case "$EXECUTOR" in
    host|vm) ;;
    *) echo "BLOCKED — invalid .gstack/e2e-executor: '${EXECUTOR}' (expected host or vm)" >&2
       exit 2 ;;
  esac
fi
# The pin governs committed macOS UI tests only. iOS tests run on a simulator on this
# host either way, but the pin is still validated above so a typo never goes unnoticed.
if [ "$EXECUTOR" = vm ] && [ "$PLATFORM" = ios ]; then
  echo "executor=vm pin applies to macOS only — running iOS tests on the simulator" >&2
  EXECUTOR=host
fi

# The result bundle lives in a fresh temp dir, created only once every check above has
# passed — an invalid pin must not leave an empty directory behind. The bundle itself
# is kept: its path is in the JSON so the caller can open it.
RESULT_BUNDLE="$(mktemp -d)/uitests.xcresult"

# --- VM path --------------------------------------------------------------------
if [ "$EXECUTOR" = vm ]; then
  if command -v vm-e2e >/dev/null 2>&1; then
    VM_JSON="$(mktemp)"
    vm-e2e "$PWD" "$SCHEME" --only-testing "$TEST_TARGET" \
           --json "$VM_JSON" --result-bundle "$RESULT_BUNDLE" >&2
    VM_STATUS=$?
    # A rig FAULT and a test FAILURE are different events. The rig produced a usable
    # result iff the JSON parses and carries a total; anything else — empty stdout, a
    # half-written file, an `error` field, a VM that never booted — is a fault. Do NOT
    # fall back to the host here: that turns a real defect into a silently slower pass.
    # Exit 2 from the rig means "could not run" — lease, boot, transfer, timeout, or
    # zero tests executed. That is declared, not inferred, so it settles the question
    # before any JSON is read.
    if [ "$VM_STATUS" -eq 2 ]; then
      echo "E2E RIG FAILED: vm-e2e could not run (exit 2)." >&2
      jq -r '.error // empty' "$VM_JSON" 2>/dev/null >&2 || true
      echo "Not falling back to the host — a rig fault is the thing to fix, not to route around." >&2
      rm -f "$VM_JSON"
      exit 2
    fi
    # The JSON checks below stay as defence in depth, and as the only signal available
    # from a rig older than the three-valued contract. A parseable object is not
    # automatically a usable result: `{"total":1,"executed":1,"error":"copy failed"}`
    # parses, and a missing `failed` defaults to 0 — so without these checks a rig that
    # reported its own failure would print as a green summary.
    # Require: no error field, and every count that EXISTS is a number. `// 0` would
    # treat `"skipped": null` as absent, but null means unknown — executed would then
    # read total-0, higher than reality, blinding the green-and-empty check.
    if ! jq -e 'type == "object"
                and (.error // null | . == null)
                and (.total | type == "number")
                and ((has("failed") | not) or (.failed | type == "number"))
                and ((has("skipped") | not) or (.skipped | type == "number"))' "$VM_JSON" >/dev/null 2>&1; then
      echo "E2E RIG FAILED: vm-e2e produced no usable result (exit ${VM_STATUS})." >&2
      jq -r '.error // empty' "$VM_JSON" 2>/dev/null >&2 || true
      echo "Not falling back to the host — a rig fault is the thing to fix, not to route around." >&2
      rm -f "$VM_JSON"
      exit 2
    fi
    # ALWAYS derive `executed` from the two counts just validated —
    # never trust the rig's own field. A present-but-non-numeric `.executed` would pass
    # the guard above and then make `[ -eq 0 ]` fail with status 2; without `set -e` the
    # script would carry on and exit 0. Deriving removes it from the trust surface.
    SKIPPED=$(jq -r '.skipped // 0' "$VM_JSON")
    FAILED=$(jq -r '.failed // 0' "$VM_JSON")
    EXECUTED=$(( $(jq -r '.total' "$VM_JSON") - SKIPPED ))
    jq --argjson ex "$EXECUTED" '. + {executor: "vm", executed: $ex}' "$VM_JSON"
    rm -f "$VM_JSON"
    echo "executor=vm  skipped=${SKIPPED}  executed=${EXECUTED}" >&2
    [ "$EXECUTED" -eq 0 ] && { echo "FAILED: 0 tests executed — green and empty is not a pass." >&2; exit 1; }
    [ "$FAILED" -ne 0 ] && exit 1
    # The counts can look clean while the rig still failed — an xcodebuild
    # infrastructure error, a transfer that half-completed. The rig's own exit code
    # carries that, so never discard it just because the summary parsed.
    if [ "$VM_STATUS" -ne 0 ]; then
      echo "vm-e2e exited ${VM_STATUS} despite a clean-looking summary — treating as failure." >&2
      exit "$VM_STATUS"
    fi
    exit 0
  fi
  # Rig absent is NOT a rig fault: a committed `vm` pin must not brick the repo on
  # every Mac without the rig. Run on the host, but never silently.
  echo "executor=vm requested, rig not found on this host — running on host without lease" >&2
  # CI variables do not cover `claude --print` or a scheduled run, and `[ ! -t 1 ]` is
  # useless here because an agent's Bash tool always pipes stdout — it would refuse
  # every interactive run too. So the caller, which actually knows the session kind,
  # says so via E2E_NONINTERACTIVE; /e2e-route sets it.
  if [ -n "${CI:-}${GITHUB_ACTIONS:-}${E2E_NONINTERACTIVE:-}" ]; then
    echo "Refusing in a non-interactive session: nobody reads that warning, and an" >&2
    echo "unleased host run can collide with another. Install the rig or pin host." >&2
    exit 2
  fi
  EXECUTOR="vm→host-fallback"
fi

# --- Host path ------------------------------------------------------------------
if [ "$PLATFORM" = ios ]; then
  # Pick a simulator by UDID. Never hardcode a model name: Xcode ships a rolling set
  # and drops old ones, and a stale name fails as "Unable to find a device matching
  # the provided destination specifier" — which reads as a broken project rather than
  # a dead device name. Targeting by id= is also exact, so it cannot match a Pro model
  # when you meant the base model, and it does not miss an SE.
  UDID="$(xcrun simctl list devices available | grep 'iPhone' | grep -oiE '[0-9A-F]{8}-([0-9A-F]{4}-){3}[0-9A-F]{12}' | head -1)"
  if [ -z "$UDID" ]; then
    echo "No iPhone simulator available. Install a runtime: Xcode > Settings > Components." >&2
    exit 2
  fi
  DEST="platform=iOS Simulator,id=${UDID}"
  echo "(using iPhone simulator ${UDID})" >&2
else
  DEST="platform=macOS"
  # Unattended UI tests need automation permission; warn, do not stop — the run may
  # still be watched by a human who can grant it.
  automationmodetool 2>&1 | grep -c 'DOES NOT REQUIRE' >/dev/null 2>&1 || \
    echo "note: could not confirm automation mode; a UI test may stall on a permission prompt" >&2
fi

# Run the tests. Capture xcodebuild's OWN exit status via PIPESTATUS — piping into
# `tail` would otherwise mask a non-zero status (tail returns 0), making a failing
# committed-regression run look green in CI.
xcodebuild test \
  -scheme "$SCHEME" \
  -destination "$DEST" \
  -only-testing:"${TEST_TARGET}" \
  -resultBundlePath "$RESULT_BUNDLE" \
  -quiet 2>&1 | tail -50
TEST_STATUS=${PIPESTATUS[0]}

# Parse xcresult to JSON summary (Xcode 16+); fall back to plaintext on older Xcode.
# `.testFailures` is null/absent on an all-green run; `(.testFailures // [])` guards
# `null | .[]` so passing runs still emit clean JSON instead of falling back.
SUMMARY=$(xcrun xcresulttool get test-results summary --path "$RESULT_BUNDLE" --format json 2>/dev/null \
  | jq --arg ex "$EXECUTOR" --arg rb "$RESULT_BUNDLE" \
      '{total: .totalTestCount, passed: .passedTests, failed: .failedTests,
        skipped: (.skippedTests // 0),
        executed: (if .totalTestCount == null then null else .totalTestCount - (.skippedTests // 0) end),
        executor: $ex, xcresult: $rb,
        results: [((.testFailures // [])[]) | {test: .testIdentifier, file: .sourceCodeContext.location.filePath, line: .sourceCodeContext.location.lineNumber, message: .failureText}]}' 2>/dev/null)

if [ -n "$SUMMARY" ]; then
  printf '%s\n' "$SUMMARY"
  TOTAL=$(printf '%s' "$SUMMARY" | jq -r '.total')
  SKIPPED=$(printf '%s' "$SUMMARY" | jq -r '.skipped')
  # Validate the two counts everything else derives from, and DERIVE executed from
  # them rather than trusting a field: a summary with `.totalTestCount` absent gives
  # `executed: null`, `[ null -eq 0 ]` only prints an error, and without `set -e` the
  # script would then exit with xcodebuild's own status — a false green.
  case "$TOTAL$SKIPPED" in ''|*[!0-9]*)
    echo "FAILED: xcresult summary lacks integer counts (total=${TOTAL:-?} skipped=${SKIPPED:-?}) — cannot verify anything ran." >&2
    exit 2 ;;
  esac
  EXECUTED=$((TOTAL - SKIPPED))
  echo "executor=${EXECUTOR}  skipped=${SKIPPED}  executed=${EXECUTED}" >&2
  # "Green and empty" — everything skipped, nothing run, exit 0 — reads as success and
  # is the most dangerous result this pipeline can produce. `executed` is the number
  # that says whether anything actually happened.
  if [ "$EXECUTED" -le 0 ]; then
    echo "FAILED: 0 tests executed — check fixtures and -only-testing." >&2
    exit 1
  fi
else
  echo "(Xcode 16+ JSON summary unavailable — plaintext follows; the executed-count guard cannot run)" >&2
  xcrun xcresulttool get --path "$RESULT_BUNDLE" 2>/dev/null | tail -100 || true
  [ "$TEST_STATUS" -ne 0 ] && exit "$TEST_STATUS"
  echo "FAILED: could not verify that any test executed — exit 2 rather than a green nobody can check." >&2
  exit 2
fi

# Exit with the REAL test status so CI / committed-regression runs fail when tests fail.
exit "$TEST_STATUS"
