import { describe, test, expect } from "bun:test";
import { esc, statusBadge, renderHero, renderFooter } from "../src/helpers/render.ts";
import { extractSection, tokenize, renderFullBody } from "../src/helpers/markdown.ts";
import { levenshtein, closestMatch } from "../src/helpers/levenshtein.ts";

describe("esc", () => {
  test("escapes <>&\"'", () => {
    expect(esc("<script>alert(1)</script>")).toBe(
      "&lt;script&gt;alert(1)&lt;/script&gt;"
    );
    expect(esc('"foo"')).toBe("&quot;foo&quot;");
    expect(esc("a & b")).toBe("a &amp; b");
    expect(esc("it's")).toBe("it&#39;s");
  });
  test("no-op on safe strings", () => {
    expect(esc("Hello, world!")).toBe("Hello, world!");
  });
  test("handles null/undefined", () => {
    expect(esc(null)).toBe("");
    expect(esc(undefined)).toBe("");
  });
  test("coerces numbers and booleans to string", () => {
    expect(esc(42)).toBe("42");
    expect(esc(true)).toBe("true");
  });
});

describe("statusBadge", () => {
  test("renders DRAFT", () => {
    expect(statusBadge("DRAFT")).toContain("status-draft");
    expect(statusBadge("DRAFT")).toContain("DRAFT");
  });
  test("escapes unknown status", () => {
    const out = statusBadge("<script>");
    expect(out).not.toContain("<script>");
    expect(out).toContain("&lt;script&gt;");
  });
  test("empty for undefined status", () => {
    expect(statusBadge(undefined)).toBe("");
  });
});

describe("renderHero", () => {
  test("includes title and status", () => {
    const out = renderHero({ title: "My doc", status: "APPROVED" });
    expect(out).toContain("My doc");
    expect(out).toContain("APPROVED");
    expect(out).toContain("status-approved");
  });
  test("escapes title with HTML entities", () => {
    const out = renderHero({ title: "<script>alert(1)</script>" });
    expect(out).not.toContain("<script>alert(1)</script>");
    expect(out).toContain("&lt;script&gt;");
  });
  test("supersedes link when provided", () => {
    const out = renderHero({
      title: "x",
      supersedesPath: "prior.md",
    });
    expect(out).toContain("Supersedes:");
    expect(out).toContain("prior.md");
  });
});

describe("renderFooter", () => {
  test("includes back-link to MD", () => {
    const out = renderFooter({ mdPath: "../foo.md" });
    expect(out).toContain('href="../foo.md"');
    expect(out).toContain("View source MD");
  });
  test("uses generator field when present", () => {
    const out = renderFooter({ mdPath: "x.md", generator: "office-hours" });
    expect(out).toContain("Generated by /office-hours");
  });
  test("falls back to superpowers-gstack when generator missing", () => {
    const out = renderFooter({ mdPath: "x.md" });
    expect(out).toContain("Generated by superpowers-gstack");
  });
});

describe("extractSection", () => {
  const md = `# Title

## Premises
- P1
- P2

## Approaches Considered
Body text.

## Empty section
`;
  const tokens = tokenize(md);

  test("finds heading and returns tokens until next H2", () => {
    const sec = extractSection(tokens, "Premises");
    expect(sec).not.toBeNull();
    expect(sec!.length).toBeGreaterThan(0);
    // first token after heading should be a list with P1, P2
    const list = sec!.find((t) => t.type === "list");
    expect(list).toBeDefined();
  });

  test("heading at end of doc", () => {
    const sec = extractSection(tokens, "Empty section");
    expect(sec).not.toBeNull();
    expect(sec!.length).toBe(0);
  });

  test("heading missing returns null", () => {
    expect(extractSection(tokens, "Nonexistent")).toBeNull();
  });

  test("case-insensitive matching", () => {
    expect(extractSection(tokens, "PREMISES")).not.toBeNull();
    expect(extractSection(tokens, "premises")).not.toBeNull();
  });

  test("duplicate headings — first wins", () => {
    const dupMd = `## First\nA\n## First\nB\n## Other\n`;
    const dupTokens = tokenize(dupMd);
    const sec = extractSection(dupTokens, "First");
    expect(sec).not.toBeNull();
    const para = sec!.find((t) => t.type === "paragraph");
    expect((para as any)?.text).toBe("A");
  });
});

describe("renderFullBody (DOMPurify sanitization)", () => {
  test("strips <script> from body", () => {
    const html = renderFullBody("# Hi\n<script>alert(1)</script>");
    expect(html).not.toContain("<script");
    expect(html).not.toContain("alert(1)");
  });

  test("strips on* handlers", () => {
    const html = renderFullBody('<img src="x" onerror="alert(1)">');
    expect(html).not.toContain("onerror");
  });

  test("preserves markdown formatting", () => {
    const html = renderFullBody("**bold** *italic* `code`");
    expect(html).toContain("<strong>bold</strong>");
    expect(html).toContain("<em>italic</em>");
    expect(html).toContain("<code>code</code>");
  });
});

describe("levenshtein", () => {
  test("identical strings = 0", () => {
    expect(levenshtein("abc", "abc")).toBe(0);
  });
  test("single substitution = 1", () => {
    expect(levenshtein("abc", "abd")).toBe(1);
  });
  test("insertion = 1", () => {
    expect(levenshtein("abc", "abcd")).toBe(1);
  });
  test("empty string", () => {
    expect(levenshtein("", "abc")).toBe(3);
    expect(levenshtein("abc", "")).toBe(3);
  });
});

describe("closestMatch", () => {
  const types = ["design-doc", "handoff", "plan"];

  test("finds typo with underscore", () => {
    expect(closestMatch("design_doc", types)).toBe("design-doc");
  });
  test("finds missing letter", () => {
    expect(closestMatch("handof", types)).toBe("handoff");
  });
  test("returns null for completely unrelated string", () => {
    expect(closestMatch("xyzqwerty", types)).toBe(null);
  });
  test("exact match returns the match", () => {
    expect(closestMatch("plan", types)).toBe("plan");
  });
  test("threshold boundary", () => {
    // distance 2 should match, distance 3 should not
    expect(closestMatch("ab", ["abcd"], 3)).toBe("abcd"); // dist 2 → matches
    expect(closestMatch("ab", ["abcde"], 3)).toBe(null); // dist 3 → no match
  });
});
