import { describe, test, expect } from "bun:test";
import { renderDesignDoc } from "../src/render/designDoc.ts";
import { renderHandoff } from "../src/render/handoff.ts";
import { renderPlan } from "../src/render/plan.ts";
import { renderGeneric } from "../src/render/generic.ts";
import type { DesignDocFM, HandoffFM, PlanFM } from "../src/schemas.ts";

const CSS = "../styles/companion.css";

describe("renderDesignDoc", () => {
  const fm: DesignDocFM = {
    type: "design-doc",
    title: "Test design",
    status: "APPROVED",
    mode: "builder",
    branch: "main",
    created: "2026-05-15T12:00:00Z",
    generator: "office-hours",
  };

  test("full render includes hero with title and status", () => {
    const html = renderDesignDoc({
      frontmatter: fm,
      body: `## Problem Statement\nReal problem.\n\n## Premises\n- P1\n## Recommended Approach\nDo X.`,
      mdPath: "test.md",
      cssHref: CSS,
    });
    expect(html).toContain("Test design");
    expect(html).toContain("APPROVED");
    expect(html).toContain("Real problem");
    expect(html).toContain("Recommended Approach");
    expect(html).toContain("View source MD");
  });

  test("missing H2 section is silent no-op", () => {
    const html = renderDesignDoc({
      frontmatter: fm,
      body: `## Problem Statement\nOnly this.`,
      mdPath: "test.md",
      cssHref: CSS,
    });
    expect(html).toContain("Problem Statement");
    expect(html).not.toContain("Premises");
    expect(html).not.toContain("Recommended Approach");
  });

  test("title with HTML entities is escaped", () => {
    const html = renderDesignDoc({
      frontmatter: { ...fm, title: "<script>alert(1)</script>" },
      body: "## Problem Statement\nx",
      mdPath: "test.md",
      cssHref: CSS,
    });
    // Title appears in <title> tag AND in <h1> — both must be escaped
    expect(html).not.toContain("<script>alert(1)</script>");
    expect(html).toContain("&lt;script&gt;");
  });

  test("supersedes renders as link", () => {
    const html = renderDesignDoc({
      frontmatter: { ...fm, supersedes: "prior-design.md" },
      body: "## Problem Statement\nx",
      mdPath: "test.md",
      cssHref: CSS,
    });
    expect(html).toContain("Supersedes:");
    expect(html).toContain("prior-design.md");
  });

  test("body script tag is stripped", () => {
    const html = renderDesignDoc({
      frontmatter: fm,
      body: `## Problem Statement\n<script>alert(1)</script>`,
      mdPath: "test.md",
      cssHref: CSS,
    });
    expect(html).not.toContain("<script>alert(1)</script>");
  });

  test("footer falls back when generator absent", () => {
    const { generator, ...noGen } = fm;
    const html = renderDesignDoc({
      frontmatter: noGen as DesignDocFM,
      body: "## Problem Statement\nx",
      mdPath: "test.md",
      cssHref: CSS,
    });
    expect(html).toContain("Generated by superpowers-gstack");
    expect(html).not.toContain("Generated by /");
  });
});

describe("renderHandoff", () => {
  const fm: HandoffFM = {
    session_end: "2026-05-15T16:30:00+02:00",
    branch: "main",
    commit_at_handoff: "abc1234",
    mode: "manual",
    active_task: "htmlify-3",
    status: "in_progress",
    completed: ["htmlify-1", "htmlify-2"],
    remaining: ["htmlify-3", "htmlify-4"],
    next_step: "Implement renderHandoff layout",
    env: { test_cmd: "bun test" },
  };

  test("renders next_step as title", () => {
    const html = renderHandoff({ frontmatter: fm, body: "", mdPath: "h.md", cssHref: CSS });
    expect(html).toContain("Implement renderHandoff layout");
  });

  test("task chips include completed (strikethrough class) + remaining", () => {
    const html = renderHandoff({ frontmatter: fm, body: "", mdPath: "h.md", cssHref: CSS });
    expect(html).toContain("htmlify-1");
    expect(html).toContain("htmlify-2");
    expect(html).toContain("htmlify-3");
    expect(html).toContain("task-chip done");
    expect(html).toContain("Completed (2)");
    expect(html).toContain("Remaining (2)");
  });

  test("env block renders", () => {
    const html = renderHandoff({ frontmatter: fm, body: "", mdPath: "h.md", cssHref: CSS });
    expect(html).toContain("test_cmd: bun test");
  });

  test("status badge rendered", () => {
    const html = renderHandoff({ frontmatter: fm, body: "", mdPath: "h.md", cssHref: CSS });
    expect(html).toContain("status-in_progress");
    expect(html).toContain("in_progress");
  });

  test("empty completed/remaining renders 'None'", () => {
    const empty: HandoffFM = {
      ...fm,
      completed: [],
      remaining: [],
    };
    const html = renderHandoff({ frontmatter: empty, body: "", mdPath: "h.md", cssHref: CSS });
    // tasksBlock is empty if both arrays are empty, so no Tasks card at all
    expect(html).not.toContain("Tasks");
  });
});

describe("renderPlan", () => {
  const fm: PlanFM = {
    type: "plan",
    title: "Test plan",
    status: "DRAFT",
    phases: [
      { id: "p1", name: "Setup", status: "done", tasks: ["init repo"] },
      { id: "p2", name: "Core", status: "in_progress" },
      { id: "p3", name: "Ship", status: "pending" },
    ],
  };

  test("renders all phases with status badges", () => {
    const html = renderPlan({ frontmatter: fm, body: "", mdPath: "p.md", cssHref: CSS });
    expect(html).toContain("Setup");
    expect(html).toContain("Core");
    expect(html).toContain("Ship");
    expect(html).toContain("status-done");
    expect(html).toContain("status-in_progress");
    expect(html).toContain("status-pending");
  });

  test("progress count in hero", () => {
    const html = renderPlan({ frontmatter: fm, body: "", mdPath: "p.md", cssHref: CSS });
    expect(html).toContain("1 / 3 phases done");
  });

  test("phase tasks render as list", () => {
    const html = renderPlan({ frontmatter: fm, body: "", mdPath: "p.md", cssHref: CSS });
    expect(html).toContain("init repo");
  });

  test("empty phases omits Phases card", () => {
    const html = renderPlan({
      frontmatter: { ...fm, phases: [] },
      body: "",
      mdPath: "p.md",
      cssHref: CSS,
    });
    expect(html).not.toContain('<h2>Phases</h2>');
  });
});

describe("renderGeneric", () => {
  test("includes fallback banner", () => {
    const html = renderGeneric({
      frontmatter: {},
      body: "# Hello\n\nSome content",
      mdPath: "x.md",
      cssHref: CSS,
    });
    expect(html).toContain("fallback-banner");
    expect(html).toContain("predates the schema");
  });

  test("renders full body via marked + DOMPurify", () => {
    const html = renderGeneric({
      frontmatter: {},
      body: "**bold**\n\n<script>bad()</script>",
      mdPath: "x.md",
      cssHref: CSS,
    });
    expect(html).toContain("<strong>bold</strong>");
    expect(html).not.toContain("<script>bad()</script>");
  });

  test("uses title from frontmatter if present", () => {
    const html = renderGeneric({
      frontmatter: { title: "Custom title" },
      body: "",
      mdPath: "x.md",
      cssHref: CSS,
    });
    expect(html).toContain("Custom title");
  });

  test("falls back to filename when no title", () => {
    const html = renderGeneric({
      frontmatter: {},
      body: "",
      mdPath: "/some/path/my-file.md",
      cssHref: CSS,
    });
    expect(html).toContain("my-file");
  });

  test("footer present with back-link", () => {
    const html = renderGeneric({
      frontmatter: {},
      body: "",
      mdPath: "x.md",
      cssHref: CSS,
    });
    expect(html).toContain("View source MD");
    expect(html).toContain('href="x.md"');
  });
});
