#!/usr/bin/env bash
#
# tests/integration/test_adapt_growth_gate.sh
#
# Verifies that /adapt's growth check (2.48.0) refuses to silently replace a
# marker-managed section that has grown past its block.
#
# The regression this guards is the QUIET one: a run that reports
# "Nothing project-authored was removed." while the diff says otherwise. So the
# assertions read the FILE, never the report.
#
# --print is non-interactive, so the gate's rule 4 (preserving branch) is the
# path under test: the section must be left at its old version, not replaced.
#
# Cost: ~1-2 minutes and a few cents. Requires ANTHROPIC_API_KEY or an active
# Claude Code session.
#
# Usage: bash tests/integration/test_adapt_growth_gate.sh
# Exit codes: 0 = pass, 1 = assertion failed, 2 = setup error.

set -uo pipefail

PLUGIN_DIR="$(cd "$(dirname "$0")/../.." && pwd)"
FIXTURE="$PLUGIN_DIR/tests/fixtures/adapt-growth/CLAUDE.md"
FAILURES=()

if ! command -v claude >/dev/null 2>&1; then
  echo "SETUP ERROR: claude CLI not found in PATH." >&2
  exit 2
fi
if [ ! -f "$FIXTURE" ]; then
  echo "SETUP ERROR: fixture missing at $FIXTURE" >&2
  exit 2
fi

WORK="$(mktemp -d)"
CLEAN_PASS=0
cleanup() {
  if [ "$CLEAN_PASS" = 1 ]; then
    rm -rf "$WORK"
  else
    echo "(work dir kept for inspection: $WORK)" >&2
  fi
}
trap cleanup EXIT
cp "$FIXTURE" "$WORK/CLAUDE.md"
mkdir -p "$WORK/.gstack" && echo "ios" > "$WORK/.gstack/track"
git -C "$WORK" init -q && git -C "$WORK" add -A
git -C "$WORK" -c user.email=t@t -c user.name=t commit -qm "fixture"

echo "Running /adapt against $WORK ..."
# The prompt states the CONDITION, never the desired action. Telling /adapt to
# "continue without stopping to ask" would read as an override of the growth gate
# itself, and the test would then prove only that /adapt obeys the last thing it
# was told. "Nobody can answer" is the fact rule 4 keys on; what /adapt does with
# that fact is what is under test.
( cd "$WORK" && claude --print --plugin-dir "$PLUGIN_DIR" \
    "/superpowers-gstack:adapt This session is \`claude --print\`: there is no interactive terminal, no one is reading the output while it runs, and any question you ask will go unanswered — no later message is coming. Context you would otherwise have to ask for: this is an iOS SwiftUI app, .gstack/track is ios, and its CLAUDE.md was generated by an old plugin version. Treat this paragraph as my answer to the Step 2 stack confirmation and the Step 4 'shall I proceed' — both are confirmed." \
    ) > "$WORK/run.log" 2>&1
echo "(exit $?; log at $WORK/run.log)"

assert() {  # $1 = description, $2 = 0/1 condition result
  if [ "$2" -eq 0 ]; then echo "PASS: $1"; else echo "FAIL: $1"; FAILURES+=("$1"); fi
}

# Precondition, not an assertion: if /adapt never reached Step 5, no snapshot
# exists and every assertion below would read the untouched fixture — a PASS
# that proves nothing. That is worse than a clear "inconclusive", so this is
# a hard gate, not assertion 1.
if [ ! -f "$WORK/.gstack/CLAUDE.md.pre-adapt" ]; then
  echo "SETUP ERROR: /adapt never reached Step 5 — no .gstack/CLAUDE.md.pre-adapt snapshot." >&2
  echo "  The remaining assertions read the fixture file, so they would pass vacuously." >&2
  echo "  This is INCONCLUSIVE, not a pass and not a growth-check failure." >&2
  echo "  Work dir kept for inspection: $WORK" >&2
  exit 2
fi

# Precondition, not an assertion: verify the fixture's own premise instead of
# assuming it. The growth check only fires above 1.5x (section lines vs. block
# lines); a fixture that doesn't actually cross that ratio would make
# assertion 3 test a mechanism that never ran, and nothing else in this script
# would notice. Derive both counts from the real files — never hardcode the
# block's line count, since it grows with the block's own version bumps.
BLOCK_FILE="$PLUGIN_DIR/skills/setup-routing/blocks/xcode-tools.md"
SECTION_START=$(grep -n '^## Native Apple development tools' "$FIXTURE" | head -1 | cut -d: -f1)
SECTION_END=$(awk -v start="$SECTION_START" 'NR>start && /^## /{print NR-1; exit}' "$FIXTURE")
[ -n "$SECTION_END" ] || SECTION_END=$(wc -l < "$FIXTURE")
SECTION_LINES=$((SECTION_END - SECTION_START + 1))
BLOCK_LINES=$(wc -l < "$BLOCK_FILE" | tr -d ' ')
RATIO=$(LC_NUMERIC=C awk -v s="$SECTION_LINES" -v b="$BLOCK_LINES" 'BEGIN { printf "%.2f", s / b }')
if ! LC_NUMERIC=C awk -v s="$SECTION_LINES" -v b="$BLOCK_LINES" 'BEGIN { exit !(s > 1.5 * b) }'; then
  echo "SETUP ERROR: fixture section is $SECTION_LINES lines against a $BLOCK_LINES-line block (${RATIO}x)." >&2
  echo "  The growth check fires above 1.5x, so this fixture cannot exercise it and" >&2
  echo "  assertion 3 would test a mechanism that never ran. INCONCLUSIVE, not a pass." >&2
  exit 2
fi
echo "Fixture premise verified: section is $SECTION_LINES lines against a $BLOCK_LINES-line block (${RATIO}x, gate fires above 1.5x)."

# 2. Every sentinel line survives. This is the assertion that matters: it reads
#    the file, so a run that CLAIMS nothing was removed still fails here.
MISSING=0
for n in 001 002 003 004 005; do
  grep -q "SENTINEL-LINE-$n" "$WORK/CLAUDE.md" || { echo "  lost SENTINEL-LINE-$n"; MISSING=1; }
done
[ "$MISSING" -eq 0 ]; assert "all 5 project-authored sentinel lines survive" $?

# 3. The grown section was NOT silently upgraded to v6 — non-interactive runs
#    take the preserving branch.
! grep -q "gstack-xcode-tools-v6" "$WORK/CLAUDE.md"; assert "grown section left at its old marker, not replaced" $?

# 4. The mandatory Removed block is present even though nothing was removed — an
#    absent block reads as "not checked", the state it exists to prevent.
grep -qi "Removed (not plugin prose)" "$WORK/run.log"; assert "report contains the Removed block" $?

# 5. The deferral NAMES its section. A bare header proves only that a template
#    was pasted; the section name is the part that tells the user what happened,
#    and it is what distinguishes a real deferral from a report that printed the
#    label and moved on.
awk '/[Dd]eferred \(grown past its block/{f=1; next} f' "$WORK/run.log" \
  | head -20 | grep -qi "Native Apple development tools"
assert "report names the deferred section under the Deferred block" $?

echo ""
if [ ${#FAILURES[@]} -eq 0 ]; then
  echo "test_adapt_growth_gate: PASS"
  CLEAN_PASS=1
  exit 0
fi
printf 'test_adapt_growth_gate: %d assertion(s) failed\n' "${#FAILURES[@]}"
printf '  - %s\n' "${FAILURES[@]}"
exit 1
