#!/usr/bin/env bash
#
# tests/integration/test_adapt_growth_gate.sh
#
# Verifies that /adapt's growth check (2.48.0) refuses to silently replace a
# marker-managed section that has grown past its block.
#
# The regression this guards is the QUIET one: a run that reports
# "Nothing project-authored was removed." while the diff says otherwise. So the
# assertions read the FILE, never the report.
#
# --print is non-interactive, so the gate's rule 4 (preserving branch) is the
# path under test: the section must be left at its old version, not replaced.
#
# Cost: ~1-2 minutes and a few cents. Requires ANTHROPIC_API_KEY or an active
# Claude Code session.
#
# Usage: bash tests/integration/test_adapt_growth_gate.sh
# Exit codes: 0 = pass, 1 = assertion failed, 2 = setup error.

set -uo pipefail

PLUGIN_DIR="$(cd "$(dirname "$0")/../.." && pwd)"
FIXTURE="$PLUGIN_DIR/tests/fixtures/adapt-growth/CLAUDE.md"
FAILURES=()

if ! command -v claude >/dev/null 2>&1; then
  echo "SETUP ERROR: claude CLI not found in PATH." >&2
  exit 2
fi
if [ ! -f "$FIXTURE" ]; then
  echo "SETUP ERROR: fixture missing at $FIXTURE" >&2
  exit 2
fi

WORK="$(mktemp -d)"
CLEAN_PASS=0
cleanup() {
  if [ "$CLEAN_PASS" = 1 ]; then
    rm -rf "$WORK"
  else
    echo "(work dir kept for inspection: $WORK)" >&2
  fi
}
trap cleanup EXIT
cp "$FIXTURE" "$WORK/CLAUDE.md"
mkdir -p "$WORK/.gstack" && echo "ios" > "$WORK/.gstack/track"
git -C "$WORK" init -q && git -C "$WORK" add -A
git -C "$WORK" -c user.email=t@t -c user.name=t commit -qm "fixture"

echo "Running /adapt against $WORK ..."
( cd "$WORK" && claude --print --plugin-dir "$PLUGIN_DIR" \
    "/superpowers-gstack:adapt Non-interactive run — nobody can answer follow-up questions. Context for your Step 2 confirmation: this is an iOS SwiftUI app, .gstack/track is ios, and its CLAUDE.md was generated by an old plugin version. I confirm in advance that your project analysis is correct — treat this paragraph as my answer to the Step 2 confirmation question and continue through Step 5 and Step 6 without stopping to ask." \
    ) > "$WORK/run.log" 2>&1
echo "(exit $?; log at $WORK/run.log)"

assert() {  # $1 = description, $2 = 0/1 condition result
  if [ "$2" -eq 0 ]; then echo "PASS: $1"; else echo "FAIL: $1"; FAILURES+=("$1"); fi
}

# Precondition, not an assertion: if /adapt never reached Step 5, no snapshot
# exists and every assertion below would read the untouched fixture — a PASS
# that proves nothing. That is worse than a clear "inconclusive", so this is
# a hard gate, not assertion 1.
if [ ! -f "$WORK/.gstack/CLAUDE.md.pre-adapt" ]; then
  echo "SETUP ERROR: /adapt never reached Step 5 — no .gstack/CLAUDE.md.pre-adapt snapshot." >&2
  echo "  The remaining assertions read the fixture file, so they would pass vacuously." >&2
  echo "  This is INCONCLUSIVE, not a pass and not a growth-check failure." >&2
  echo "  Work dir kept for inspection: $WORK" >&2
  exit 2
fi

# 2. Every sentinel line survives. This is the assertion that matters: it reads
#    the file, so a run that CLAIMS nothing was removed still fails here.
MISSING=0
for n in 001 002 003 004 005; do
  grep -q "SENTINEL-LINE-$n" "$WORK/CLAUDE.md" || { echo "  lost SENTINEL-LINE-$n"; MISSING=1; }
done
[ "$MISSING" -eq 0 ]; assert "all 5 project-authored sentinel lines survive" $?

# 3. The grown section was NOT silently upgraded to v6 — non-interactive runs
#    take the preserving branch.
! grep -q "gstack-xcode-tools-v6" "$WORK/CLAUDE.md"; assert "grown section left at its old marker, not replaced" $?

# 4. The report names the deferral rather than passing over it in silence.
grep -qi "Removed (not plugin prose)" "$WORK/run.log"; assert "report contains the Removed block" $?

echo ""
if [ ${#FAILURES[@]} -eq 0 ]; then
  echo "test_adapt_growth_gate: PASS"
  CLEAN_PASS=1
  exit 0
fi
printf 'test_adapt_growth_gate: %d assertion(s) failed\n' "${#FAILURES[@]}"
printf '  - %s\n' "${FAILURES[@]}"
exit 1
