// Shared HTML render helpers (D3).
// All frontmatter values must go through `esc()` before interpolation (D4).

const HTML_ENTITIES: Record<string, string> = {
  "&": "&amp;",
  "<": "&lt;",
  ">": "&gt;",
  '"': "&quot;",
  "'": "&#39;",
};

export function esc(value: unknown): string {
  if (value === null || value === undefined) return "";
  return String(value).replace(/[&<>"']/g, (c) => HTML_ENTITIES[c]);
}

export type StatusLevel = "draft" | "approved" | "shipped" | "in_progress" | "blocked" | "ready_to_review" | "done" | "pending" | "neutral";

const STATUS_LEVEL: Record<string, StatusLevel> = {
  DRAFT: "draft",
  APPROVED: "approved",
  SHIPPED: "shipped",
  in_progress: "in_progress",
  blocked: "blocked",
  ready_to_review: "ready_to_review",
  done: "done",
  pending: "pending",
};

export function statusBadge(status: string | undefined): string {
  if (!status) return "";
  const level = STATUS_LEVEL[status] ?? "neutral";
  return `<span class="status-badge status-${esc(level)}">${esc(status)}</span>`;
}

export function typeBadge(type: string): string {
  return `<span class="type-badge type-${esc(type)}">${esc(type)}</span>`;
}

export interface HeroParts {
  title: string;
  status?: string;
  meta?: Array<{ label: string; value: string }>;
  supersedesPath?: string | null;
}

export function renderHero(parts: HeroParts): string {
  const status = statusBadge(parts.status);
  const meta = (parts.meta ?? [])
    .map(
      (m) =>
        `<dt>${esc(m.label)}</dt><dd>${esc(m.value)}</dd>`
    )
    .join("");
  const supersedes = parts.supersedesPath
    ? `<p class="supersedes">Supersedes: <a href="${esc(parts.supersedesPath)}">${esc(parts.supersedesPath)}</a></p>`
    : "";
  return `
<header class="hero">
  <div class="hero-title">
    <h1>${esc(parts.title)}</h1>
    ${status}
  </div>
  ${meta ? `<dl class="hero-meta">${meta}</dl>` : ""}
  ${supersedes}
</header>`;
}

export interface FooterParts {
  mdPath: string;
  generator?: string | null;
}

export function renderFooter(parts: FooterParts): string {
  const gen = parts.generator
    ? `Generated by /${esc(parts.generator)}`
    : "Generated by superpowers-gstack";
  return `
<footer class="companion-footer">
  <p class="back-link"><a href="${esc(parts.mdPath)}">View source MD →</a></p>
  <p class="footer-meta">${gen}</p>
</footer>`;
}

export function renderCard(opts: {
  heading: string;
  body: string;
  variant?: "default" | "accent" | "muted";
  collapsible?: boolean;
}): string {
  const variant = opts.variant ?? "default";
  const klass = `card card-${variant}`;
  if (opts.collapsible) {
    return `<details class="${klass}" open><summary><h2>${esc(opts.heading)}</h2></summary>${opts.body}</details>`;
  }
  return `<section class="${klass}"><h2>${esc(opts.heading)}</h2>${opts.body}</section>`;
}

// Inline scripts: the theme bootstrap MUST run before paint to avoid flash-of-
// wrong-theme. Persistence is in localStorage under "htmlify-theme"; values
// are "light", "dark", or absent (= follow OS).
const THEME_BOOTSTRAP = `(function(){try{var t=localStorage.getItem('htmlify-theme');if(t==='light'||t==='dark')document.documentElement.setAttribute('data-theme',t);}catch(e){}})();`;

const THEME_TOGGLE_SCRIPT = `(function(){var btn=document.querySelector('[data-theme-toggle]');if(!btn)return;function current(){var t=document.documentElement.getAttribute('data-theme');if(t)return t;return window.matchMedia('(prefers-color-scheme: dark)').matches?'dark':'light';}function update(){var t=current();var lbl=btn.querySelector('.theme-label');if(lbl)lbl.textContent=t==='dark'?'Dark':'Light';}btn.addEventListener('click',function(){var next=current()==='dark'?'light':'dark';document.documentElement.setAttribute('data-theme',next);try{localStorage.setItem('htmlify-theme',next);}catch(e){}update();});update();})();`;

export function htmlShell(opts: {
  title: string;
  cssHref: string;
  body: string;
  bodyClass?: string;
}): string {
  return `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>${esc(opts.title)}</title>
  <link rel="stylesheet" href="${esc(opts.cssHref)}">
  <script>${THEME_BOOTSTRAP}</script>
</head>
<body${opts.bodyClass ? ` class="${esc(opts.bodyClass)}"` : ""}>
<button class="theme-toggle" type="button" data-theme-toggle aria-label="Toggle theme">
  <span class="theme-glyph" aria-hidden="true"></span>
  <span class="theme-label">Light</span>
</button>
${opts.body}
<script>${THEME_TOGGLE_SCRIPT}</script>
</body>
</html>
`;
}
