#!/usr/bin/env python3
"""Lint the plugin's instruction surface (skills/, CLAUDE.md, README.md).

The 2026-07-03 system review found that 5 700 lines of SKILL.md had zero
validation — which is how a removed third-lens role kept shipping in generator
templates, three releases of work became unreachable by routing, and four
releases went out without CHANGELOG entries. This lint makes that whole drift
class impossible to reintroduce silently.

ERRORS (exit 1, CI-blocking):
  E1  SKILL.md frontmatter parses, `name` matches its directory, `description` present
  E2  cross-references resolve: `superpowers-gstack:<skill>` names and repo
      `scripts/<file>` paths mentioned in instruction files actually exist
  E3  routing coverage: every skill directory is mentioned in CLAUDE.md
  E4  plugin.json version has a matching `## [X.Y.Z]` entry in CHANGELOG.md
  E5  all `gstack-multi-lens-review-vN` markers carry the same N
  E6  no `version:` field in skill frontmatter (plugin.json is the version)
  E7  denylist: patterns that must never reappear in instruction files
      (e.g. the third-lens `sensitive` role removed in 2.18.0)
  E8  emitted blocks are single-sourced: every shared block file in
      skills/adapt/blocks/ exists, carries its version marker on the H2
      heading line, and is in the BLOCKS roster of scripts/adapt-claude-md.py
      (the one generator since 3.1.0); adapt/SKILL.md carries no inline copy
      (no marker heading, no bare block heading) and references
      PLACEHOLDERS.md. Replaced the old byte-identity drift guard in 2.33.0 —
      one source can't drift from itself.

  E10 upstream skill references resolve: every `superpowers:<name>` names a
      real Superpowers skill (roster: SUPERPOWERS_SKILLS). E2 only ever checked
      this plugin's OWN skill names, so an upstream name was unvalidated — the
      exact content the weekly auto-update job writes from release notes.

  E11 this repo's own CLAUDE.md carries a current copy of the universal blocks.
      check-plugin-version.sh exempts this repo from the /adapt nag (correctly —
      its CLAUDE.md is the SOURCE of the routing), but the exemption was wholesale,
      so the plugin prescribed discipline it never applied to itself. The region is
      generated by scripts/sync-own-claude-md.py; this fails when it goes stale.

  E12 every `{{TOKEN}}` used in a shared block has a NON-EMPTY resolution rule in
      blocks/PLACEHOLDERS.md. Without one the generators emit it verbatim into
      the project's CLAUDE.md — the exact outcome that file's preamble forbids.
      A heading alone does not count: `## `{{TOKEN}}`` with nothing under it
      documents nothing, and passed this rule until 2.48.0.

  E13 /adapt delegates every CLAUDE.md write to scripts/adapt-claude-md.py:
      the skill names the script, and carries none of the hand-surgery
      instructions the 2.x prose had (`cp CLAUDE.md`, `sed -n '<start>`, the
      Growth / Attribution check gates). Before 3.1.0 this rule pinned twenty
      sentences of that prose because a reword could silently delete a guard;
      the guards are code with tests now, and the lint only has to keep the
      model from doing the surgery itself again.

  E14 no block file carries the `emitted=` marker attribute. Generators write that
      count into a project's CLAUDE.md at emit time; stored in the source it is a
      constant that goes stale on the next edit, and the growth check would trust it.

WARNINGS (reported, exit 0):
  W1  frontmatter description over budget (target <=30 words; hard cap comes
      with the Phase-3 description rewrites)
  W2  SKILL.md body over 500 lines (bloat radar)
  W3  SUPERPOWERS_SKILLS roster disagrees with the installed Superpowers plugin
      (maintainer machines only — CI has no upstream installed, so E10's roster
      is the CI-side source of truth and this is the drift alarm for it)

Run: python3 scripts/lint-skills.py   (from the repo root or anywhere)
"""
from __future__ import annotations

import json
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
SKILLS = REPO / "skills"
DESCRIPTION_WARN_WORDS = 30
BODY_WARN_LINES = 500

# Patterns that must never reappear in instruction files (skills/, CLAUDE.md,
# README.md — CHANGELOG is history and may mention them). Add an entry whenever
# a stale-reference class is purged, so it stays purged.
DENYLIST = [
    (re.compile(r"`sensitive`\s*="), "third-lens 'sensitive' role was removed in 2.18.0"),
    (re.compile(r"--role\s+sensitive|--sensitive\b"), "third-lens --sensitive flag was removed in 2.18.0"),
    (re.compile(r"gstack-multi-lens-review-v[0-6]\b"), "stale multi-lens marker (current: v7+, 3.0.0)"),
    (re.compile(r"gstack-session-continuity-v[1-3]\b"), "stale session-continuity marker (current: v4+, 3.0.0)"),
    (re.compile(r"gstack-code-reuse-v[12]\b"), "stale code-reuse marker (current: v3+, 3.0.0)"),
    (re.compile(r"gstack-autonomy-v\d"), "the autonomy block was retired in 3.0.0 — the Claude Code harness carries the same instruction; /adapt removes the old section"),
    (re.compile(r"gstack-plan-fidelity-v[12]\b"), "stale plan-fidelity marker (current: v3+, 2.52.0)"),
    (re.compile(r"repin\s+--yes\s+--sha\b|--yes\s+--sha\b"),
     "spec-drift --sha was replaced by the one-time --token in 2.52.0"),
    (re.compile(r"gstack-routing-v[12]\b"), "stale track-routing marker (current: v3+, 3.0.0)"),
    (re.compile(r"gstack-companion-skills-v[12]\b"), "stale companion-skills marker (current: v3+, 3.0.0)"),
    (re.compile(r"gstack-git-hygiene-v[0-9]\b"), "stale git-hygiene marker (current: v10+, 3.0.0)"),
    (re.compile(r"gstack-xcode-tools-v[0-6]\b"), "stale xcode-tools marker (current: v7+, 2.53.0)"),
    # v5 hardcoded `name=iPhone 16`; Xcode had already dropped it on the author's
    # own machine, and the resulting "Unable to find a device matching the
    # provided destination specifier" reads as a broken project, not a dead name.
    (re.compile(r"name=iPhone \d"),
     "hardcoded simulator model — use {{IOS_SIMULATOR}} or resolve by UDID (2.48.0)"),
    (re.compile(r"Pi \(local|Pi \(hybrid"), "local-model (Pi) routing columns removed in v0.2 (2.27.0)"),
    (re.compile(r"start-mlx"), "MLX local-server routing removed in v0.2 (2.27.0)"),
    (re.compile(r"models\.json"), "Pi models.json runtime detection removed in v0.2 (2.27.0)"),
    (re.compile(r"WXNUGGYB2B"), "hardcoded Apple Team ID removed in 2.33.0 — use the {{DEVELOPMENT_TEAM}} placeholder"),
    # 3.0.0 removals: the adaptive lens router never reached its own skip
    # threshold in two months of records; the Gemini computer-use loop was
    # replaced by the session model's own multimodality + XcodeBuildMCP.
    (re.compile(r"cost[-_]ledger"), "the cost-ledger adaptive lens router was removed in 3.0.0"),
    # The lookbehinds exempt the two sites that must name the retired skill to remove
    # it: the script's REMOVED_SKILLS roster and the adapt skill's one-line mention.
    (re.compile(r"(?<!REMOVED_SKILLS = \(\")(?<!drops `)ios-visual-explore|computer[-_]use"), "ios-visual-explore and scripts/computer_use were removed in 3.0.0"),
    # 2.36.0 renamed the handoff persistence mode auto -> continuous; 3.0.0 dropped
    # the legacy read paths (`mode: auto`, `## Mode: auto`, typeless v1.12 frontmatter).
    (re.compile(r"auto context (guard|handoff)"),
     "renamed to 'continuous handoff' in 2.36.0 ('auto context guard' was also drifted wording in adapt)"),
    (re.compile(r"mode:\s*auto\b|##\s*Mode:\s*auto|legacy `?auto`?"),
     "legacy handoff spellings (`mode: auto`, `## Mode: auto`) are no longer read since 3.0.0 — only `mode: continuous`"),
    # Model ids and prices belong in scripts and model-routing.md, never in
    # instruction prose or emitted blocks — they went stale within weeks every time.
    (re.compile(r"gpt-5\.5|glm-5\.2|GLM-5\.2|\$\d+/\$\d+ per Mtok"),
     "hardcoded model id / price in instruction prose — name the tier or role, let the script resolve the id (3.0.0)"),
    (re.compile(r"(auto-)?chains? `?/codex review|`/codex review` \(Stage 2\)|invoke `/codex review`"),
     "gstack /review owns the Codex pass since 3.0.0 — say `/review`, never chain `/codex review` on a diff"),
    (re.compile(r"setup-htmlify-hook|htmlify-posttooluse|close every window"),
     "htmlify's Safari flow and PostToolUse hook were removed in 3.0.0 — previews go through the Artifact tool"),
    # 2.48.0: Step 6 used to ask for a diff against a file Step 5 had already
    # overwritten. An unperformable verification is always answered
    # optimistically — the fix is a real snapshot, not better wording.
    (re.compile(r"diff the old vs new CLAUDE\.md mentally"),
     "unperformable verification — diff .gstack/CLAUDE.md.pre-adapt instead (2.48.0)"),
]

# Shared emitted blocks (skills/adapt/blocks/): single source for the sections
# scripts/adapt-claude-md.py writes into a project's CLAUDE.md. Marker-carrying
# blocks must have their `<!-- gstack-<name>-vN -->` marker on the H2 heading.
BLOCKS_DIR_REL = Path("skills") / "adapt" / "blocks"
ADAPT_SCRIPT_REL = Path("scripts") / "adapt-claude-md.py"
MARKER_BLOCKS = [
    "git-hygiene.md",
    "multi-lens-review.md",
    "code-reuse.md",
    "plan-fidelity.md",
    "session-continuity.md",
    "track-routing.md",
    "xcode-tools.md",
    "companion-skills.md",
]
PLAIN_BLOCKS = ["model-routing-section.md", "PLACEHOLDERS.md"]

# E13: the hand-surgery instructions /adapt must NOT carry any more. Each was
# the site of a guard in the 2.x prose; their presence means a model is being
# asked to perform the merge itself, which is the failure class 3.1.0 closed.
ADAPT_HAND_SURGERY = (
    ("cp CLAUDE.md ", "the pre-write snapshot is the script's"),
    ("sed -n '<start>", "the section read for the growth check is the script's"),
    ("**Growth check —", "the growth gate is the script's"),
    ("**Attribution check —", "the attribution rule is the script's"),
    ("The block to insert: read `blocks/", "blocks are emitted by the script, never pasted"),
)

errors: list[str] = []
warnings: list[str] = []


def heading_text(line: str) -> str | None:
    """Normalized heading text for E8's inline-copy guard, or None if `line` is
    not a heading at all.

    A re-paste of an emitted block can wear several disguises, and each one that
    slips through reopens the drift class E8 exists to close. This tolerates:
    leading whitespace (the pre-2.36.0 Session Continuity copy hid indented
    inside a fenced example and sailed past a bare startswith("#") for four
    releases), blockquote/list prefixes, ATX closing hashes, the gstack version
    marker, and letter case. Body-only copies with no heading remain out of
    reach — a heading-keyed check cannot see them, and the CHANGELOG says so.
    """
    # Blockquote markers and whitespace strip unconditionally. A list marker
    # strips only in its real form (`- `, `* `, `+ ` with trailing space) — a
    # blanket [-*+]* class would also eat a `---` rule or a hyphenated token and
    # expose a following `#`, inventing a false-positive class that the older
    # startswith("#") check did not have (third-lens P3, 2.36.0).
    s = re.sub(r"^[\s>]*", "", line)
    s = re.sub(r"^[-*+][ \t]+", "", s)
    if not s.startswith("#"):
        return None
    s = s.lstrip("#").strip()
    # Provenance strips FIRST, because 2.49.0 writes it to the RIGHT of the
    # marker: `## X <!-- gstack-x-v2 --><!-- emitted=31 -->`. With only the
    # marker rule — anchored at `$` — that heading normalized to
    # `x <!-- gstack-x-v2 --><!-- emitted=31 -->`, so the normalizer's contract
    # and the shape the generators actually emit had drifted apart. E8's marker
    # branch reads the raw line and was never fooled; its markerless branch
    # compares against this text and would have been.
    s = re.sub(r"\s*<!-- emitted=\d+ -->\s*$", "", s)
    s = re.sub(r"\s*<!-- gstack-[a-z-]+-v\d+ -->\s*$", "", s)
    return re.sub(r"\s*#+$", "", s).strip().lower()


def documented_placeholders(text: str) -> set[str]:
    """Tokens that PLACEHOLDERS.md actually documents (E12).

    Heading membership is not documentation. `## \\`{{TOKEN}}\\`` followed
    immediately by the next heading names a placeholder and gives the generator
    nothing to resolve it with, which is the same outcome as no entry at all —
    a raw `{{TOKEN}}` in the project's CLAUDE.md. E12 accepted exactly that
    until 2.48.0, and so did its unit test.
    """
    out: set[str] = set()
    heads = list(re.finditer(r"^##\s+`\{\{([A-Z0-9_]+)\}\}`.*$", text, re.M))
    for i, m in enumerate(heads):
        nxt = re.search(r"^#{1,6} ", text[m.end():], re.M)
        end = m.end() + nxt.start() if nxt else len(text)
        if text[m.end():end].strip():
            out.add(m.group(1))
    return out


def adapt_script_blocks() -> list[str] | None:
    """The block file names scripts/adapt-claude-md.py emits (its BLOCKS roster),
    or None when the script cannot be imported — E8 then reports that itself."""
    import importlib.util
    path = REPO / ADAPT_SCRIPT_REL
    if not path.is_file():
        return None
    spec = importlib.util.spec_from_file_location("adapt_claude_md", path)
    mod = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = mod
    try:
        spec.loader.exec_module(mod)
    except Exception:
        return None
    return [b.file for b in mod.BLOCKS] + [mod.MODEL_ROUTING_FILE]


def check_adapt_delegates(text: str) -> list[str]:
    """E13: adapt/SKILL.md must name the script and carry no hand-surgery."""
    errs: list[str] = []
    if str(ADAPT_SCRIPT_REL) not in text:
        errs.append(f"E13 adapt/SKILL.md never names {ADAPT_SCRIPT_REL} — every CLAUDE.md write must go through it")
    for needle, why in ADAPT_HAND_SURGERY:
        if needle in text:
            errs.append(f"E13 adapt/SKILL.md carries {needle!r} — {why}; the model must not merge by hand")
    return errs


def bare_skill_ref_re(own_skill_names) -> "re.Pattern":
    r"""Match a bare `/skill-name` for a skill THIS plugin owns (E9).

    The boundaries do the work. Both sides must be guarded:
      `/superpowers-gstack:htmlify`  namespaced — holds no `/htmlify` substring,
                                     so it never matches in the first place
      `skills/htmlify/SKILL.md`      a path — word char before the slash
      `./htmlify/SKILL.md`           a path — trailing `/` after the name
      `/e2e-route-extra`             a longer token — trailing `-` after the name
      `/ship`, `/review`             gstack/Superpowers skills, correctly bare —
                                     excluded by not being in `own_skill_names`
    `:` is deliberately NOT in the lookbehind: it cannot protect the namespaced
    form (no `/name` there to match) and only creates misses like `label:/htmlify`.
    A trailing `\b` alone is not enough — it accepts `-` and `/`, which is how
    both false-positive classes got in. Longest-first alternation so `/e2e-route`
    is never reported as `/e2e`.
    """
    names = sorted(own_skill_names, key=len, reverse=True)
    return re.compile(r"(?<![\w/-])/(" + "|".join(map(re.escape, names)) + r")(?![\w/-])")


def frontmatter(text: str) -> dict | None:
    """Minimal YAML-ish frontmatter reader: top-level `key:` lines between --- markers.
    Values are not fully parsed (multi-line descriptions concatenate); enough for linting."""
    m = re.match(r"\A---\n(.*?)\n---\n", text, re.DOTALL)
    if not m:
        return None
    fm: dict[str, str] = {}
    key = None
    for line in m.group(1).splitlines():
        km = re.match(r"^([A-Za-z_-]+):\s*(.*)$", line)
        if km:
            key = km.group(1)
            val = km.group(2).strip()
            # A bare block-scalar indicator (|, >, with optional chomping) is not
            # content — the value is on the following indented lines. Counting the
            # `|` as a word would over-count every block-scalar description by one.
            fm[key] = "" if val in ("|", ">", "|-", "|+", ">-", ">+") else val
        elif key and (line.startswith("  ") or line.startswith("\t")):
            fm[key] = (fm[key] + " " + line.strip()).strip()
    return fm


# Upstream skills this plugin is allowed to route to (E10). Checked in rather
# than read from disk because CI has no upstream installed — a disk-only check
# would be silent exactly where it matters, on the auto-update PR.
#
# Scoped to Superpowers on purpose. gstack ships ~50 skills on a weekly cadence;
# a checked-in list that large would drift faster than it protects, and its bare
# `/name` form collides with E9's own-skill matcher. Superpowers is 14 names on a
# slow cadence, and the namespaced `superpowers:<name>` form is unambiguous.
SUPERPOWERS_SKILLS = {
    "brainstorming",
    "dispatching-parallel-agents",
    "executing-plans",
    "finishing-a-development-branch",
    "receiving-code-review",
    "requesting-code-review",
    "subagent-driven-development",
    "systematic-debugging",
    "test-driven-development",
    "using-git-worktrees",
    "using-superpowers",
    "verification-before-completion",
    "writing-plans",
    "writing-skills",
}
SUPERPOWERS_CACHE_GLOB = "plugins/cache/claude-plugins-official/superpowers/*/skills"


def installed_superpowers_skills():
    """Skill names from the newest installed Superpowers, or None if absent.

    Absent is the normal case in CI. Returning None (not an empty set) keeps the
    caller from reading "not installed" as "upstream has no skills".
    """
    dirs = sorted((Path.home() / ".claude").glob(SUPERPOWERS_CACHE_GLOB))
    if not dirs:
        return None
    newest = dirs[-1]
    return {d.name for d in newest.iterdir() if (d / "SKILL.md").is_file()}


def check_upstream_skills(path: Path, text: str) -> None:
    """E10: `superpowers:<name>` references must name a real upstream skill.

    E2 validates only THIS plugin's own skill names, so an upstream name was
    unvalidated everywhere. That is precisely the content the weekly auto-update
    job generates from release notes — a hallucinated skill would have passed
    every gate and shipped a dead routing row into every generated CLAUDE.md.
    """
    for name in set(re.findall(r"(?<!-)superpowers:([a-z0-9-]+)", text)):
        if name not in SUPERPOWERS_SKILLS:
            errors.append(
                f"E10 {path.relative_to(REPO)}: reference to unknown upstream skill "
                f"'superpowers:{name}' — not in SUPERPOWERS_SKILLS. If upstream really "
                f"added it, verify against the installed plugin and add it to the roster."
            )


def check_refs(path: Path, text: str, repo_doc: bool) -> None:
    """E2: skill-name and repo-script references must resolve.

    Path semantics learned on the lint's first run: a bare `scripts/<x>` inside a
    SKILL.md body is a USER-project path by convention (scaffolds emit
    scripts/run-uitests.sh into the target project; generated CLAUDE.md rows name
    project scripts). Repo assets are referenced via `$SKILL_DIR/../../scripts/<x>`
    — those must resolve. In repo docs (CLAUDE.md, README) bare `scripts/` refs
    mean this repo and are checked too."""
    for name in set(re.findall(r"superpowers-gstack:([a-z0-9-]+)", text)):
        if not (SKILLS / name).is_dir():
            errors.append(f"E2 {path.relative_to(REPO)}: reference to nonexistent skill 'superpowers-gstack:{name}'")
    for line in text.splitlines():
        # skip external-path lines (gstack's own skills/bin live under ~/.claude)
        if ".claude/skills" in line or "gstack/bin" in line:
            continue
        for script in set(re.findall(r"\$SKILL_DIR/\.\./\.\./scripts/([A-Za-z0-9_.-]+)", line)):
            if not (REPO / "scripts" / script).exists():
                errors.append(f"E2 {path.relative_to(REPO)}: repo-asset reference to nonexistent 'scripts/{script}'")
        if repo_doc:
            for script in set(re.findall(r"(?<![\w/.])scripts/([A-Za-z0-9_.-]+)", line)):
                if not (REPO / "scripts" / script).exists():
                    errors.append(f"E2 {path.relative_to(REPO)}: reference to nonexistent script 'scripts/{script}'")


def main() -> int:
    skill_dirs = sorted(d for d in SKILLS.iterdir() if d.is_dir())
    claude_md = (REPO / "CLAUDE.md").read_text()
    readme = (REPO / "README.md").read_text()

    # E1 + E6 + W1 + W2 per skill
    for d in skill_dirs:
        skill_md = d / "SKILL.md"
        if not skill_md.is_file():
            errors.append(f"E1 {d.name}: missing SKILL.md")
            continue
        text = skill_md.read_text()
        fm = frontmatter(text)
        if fm is None:
            errors.append(f"E1 {d.name}: no frontmatter block")
            continue
        if fm.get("name") != d.name:
            errors.append(f"E1 {d.name}: frontmatter name '{fm.get('name')}' != directory name")
        desc = fm.get("description", "")
        if not desc:
            errors.append(f"E1 {d.name}: missing/empty description")
        elif len(desc.split()) > DESCRIPTION_WARN_WORDS:
            warnings.append(f"W1 {d.name}: description is {len(desc.split())} words (target <=30 — per-session tax in every project)")
        if "version" in fm:
            errors.append(f"E6 {d.name}: frontmatter 'version:' field — plugin.json is the only version")
        if text.count("\n") > BODY_WARN_LINES:
            warnings.append(f"W2 {d.name}: SKILL.md body is {text.count(chr(10))} lines (>500 — bloat radar)")
        check_refs(skill_md, text, repo_doc=False)
        check_upstream_skills(skill_md, text)

    # E2 on CLAUDE.md + README too
    check_refs(REPO / "CLAUDE.md", claude_md, repo_doc=True)
    check_upstream_skills(REPO / "CLAUDE.md", claude_md)
    check_refs(REPO / "README.md", readme, repo_doc=True)
    check_upstream_skills(REPO / "README.md", readme)

    # E10 layer 2: the roster itself must match reality. Only runs where an
    # upstream is installed (never in CI), so it catches roster drift on a
    # maintainer's machine without making CI depend on a local install.
    _installed = installed_superpowers_skills()
    if _installed is not None:
        for missing in sorted(_installed - SUPERPOWERS_SKILLS):
            warnings.append(f"W3 SUPERPOWERS_SKILLS is missing '{missing}' — installed upstream has it; add it to the roster")
        for phantom in sorted(SUPERPOWERS_SKILLS - _installed):
            warnings.append(f"W3 SUPERPOWERS_SKILLS lists '{phantom}' — installed upstream does NOT have it; verify before routing to it")


    # E3 routing coverage
    for d in skill_dirs:
        if d.name not in claude_md:
            errors.append(f"E3 CLAUDE.md: skill '{d.name}' has no mention — unreachable by routing")

    # E4 version <-> CHANGELOG
    version = json.loads((REPO / ".claude-plugin" / "plugin.json").read_text())["version"]
    if f"## [{version}]" not in (REPO / "CHANGELOG.md").read_text():
        errors.append(f"E4 CHANGELOG.md: no entry for plugin.json version {version} — ship-worthy releases require a CHANGELOG entry")

    # E5 multi-lens marker consistency (SKILL.md files + shared block files)
    marker_versions = set()
    marker_files = [d / "SKILL.md" for d in skill_dirs]
    marker_files += sorted((REPO / BLOCKS_DIR_REL).glob("*.md")) if (REPO / BLOCKS_DIR_REL).is_dir() else []
    for f in marker_files:
        for m in re.finditer(r"gstack-multi-lens-review-v(\d+)", f.read_text()):
            marker_versions.add(m.group(1))
    if len(marker_versions) > 1:
        errors.append(f"E5 multi-lens markers disagree across skills: v{sorted(marker_versions)}")

    # E7 denylist
    targets = [(REPO / "CLAUDE.md", claude_md), (REPO / "README.md", readme)]
    targets += [(d / "SKILL.md", (d / "SKILL.md").read_text()) for d in skill_dirs if (d / "SKILL.md").is_file()]
    # Also scan the canonical routing table — the file most likely to regress a
    # purged local-model (Pi/MLX) pattern, yet it is not a SKILL.md.
    _mr = REPO / "skills" / "adapt" / "model-routing.md"
    if _mr.is_file():
        targets.append((_mr, _mr.read_text()))
    # ... and the shared emitted blocks — they ARE the generated-CLAUDE.md content.
    if (REPO / BLOCKS_DIR_REL).is_dir():
        targets += [(f, f.read_text()) for f in sorted((REPO / BLOCKS_DIR_REL).glob("*.md"))]
    # ... and the scripts themselves — user-facing messages/docstrings drift the
    # same way instruction files do (the 2.34.1 audit found `/cost-ledger pause`
    # in cli.py output after the .md sweep missed it). lint-skills.py itself is
    # exempt: it carries the patterns by definition.
    targets += [(f, f.read_text()) for pat in ("*.py", "*.sh")
                for f in sorted((REPO / "scripts").rglob(pat))
                if f.name != "lint-skills.py" and "__pycache__" not in f.parts]
    for path, text in targets:
        for pattern, why in DENYLIST:
            for i, line in enumerate(text.splitlines(), 1):
                if pattern.search(line):
                    errors.append(f"E7 {path.relative_to(REPO)}:{i}: denylisted pattern ({why})")

    # E8 single-source guard for emitted blocks (2.33.0, replaces the old
    # byte-identity drift check — one source can't drift from itself):
    #   (a) every shared block file exists;
    #   (b) marker blocks carry `<!-- gstack-<x>-vN -->` on their H2 heading line;
    #   (c) the generator — scripts/adapt-claude-md.py since 3.1.0 — lists every
    #       block in its BLOCKS roster (no orphaned block, no block it forgot);
    #   (d) adapt/SKILL.md has no inline copy — a heading line carrying a gstack
    #       marker inside a SKILL.md is a regression to hand-maintained
    #       duplication (the class the 2.27.0 pre-merge review caught) — and
    #       references PLACEHOLDERS.md, the file it resolves `--set` values from.
    blocks_dir = REPO / BLOCKS_DIR_REL
    gen_texts = {name: (SKILLS / name / "SKILL.md").read_text()
                 for name in ("adapt",)
                 if (SKILLS / name / "SKILL.md").is_file()}
    roster = adapt_script_blocks()
    if roster is None:
        errors.append(f"E8 {ADAPT_SCRIPT_REL} is missing or does not import — no generator emits the blocks")
    for fname in MARKER_BLOCKS + PLAIN_BLOCKS:
        f = blocks_dir / fname
        if not f.is_file():
            errors.append(f"E8 missing shared block file {BLOCKS_DIR_REL}/{fname}")
            continue
        if fname in MARKER_BLOCKS:
            first = f.read_text().split("\n", 1)[0]
            if not re.match(r"^## .*<!-- gstack-[a-z-]+-v\d+ -->$", first):
                errors.append(f"E8 {BLOCKS_DIR_REL}/{fname}: first line must be an H2 heading with a gstack version marker")
        if fname == "PLACEHOLDERS.md":
            for gen, text in gen_texts.items():
                if fname not in text:
                    errors.append(f"E8 {gen}/SKILL.md never references blocks/{fname} — the skill would not resolve placeholders")
        elif roster is not None and fname not in roster:
            errors.append(f"E8 {ADAPT_SCRIPT_REL} never emits blocks/{fname} — not in its BLOCKS roster")
    if roster is not None:
        for fname in roster:
            if fname not in MARKER_BLOCKS + PLAIN_BLOCKS:
                errors.append(f"E8 {ADAPT_SCRIPT_REL} emits blocks/{fname}, which MARKER_BLOCKS/PLAIN_BLOCKS do not list")
    if (blocks_dir / "model-routing-section.md").is_file():
        if "## Model Routing" not in (blocks_dir / "model-routing-section.md").read_text():
            errors.append("E8 blocks/model-routing-section.md lost its `## Model Routing` anchor")
    # Orphan guard: a blocks/*.md not in the known lists has no emitter — it
    # would silently never reach any generated CLAUDE.md.
    if blocks_dir.is_dir():
        for f in sorted(blocks_dir.glob("*.md")):
            if f.name not in MARKER_BLOCKS + PLAIN_BLOCKS:
                errors.append(f"E8 orphaned block file {BLOCKS_DIR_REL}/{f.name} — not in MARKER_BLOCKS/PLAIN_BLOCKS, no generator emits it")
    # Inline copies are forbidden WITH or WITHOUT the marker — a markerless
    # re-paste of a block heading would reopen the drift class E8 exists to
    # prevent (Codex P2 on the 2.33.0 branch caught exactly this hole).
    block_headings = set()
    for fname in MARKER_BLOCKS + ["model-routing-section.md"]:
        f = blocks_dir / fname
        if f.is_file():
            h = heading_text(f.read_text().split("\n", 1)[0])
            if h:
                block_headings.add(h)
    for gen, text in gen_texts.items():
        for i, line in enumerate(text.splitlines(), 1):
            h = heading_text(line)
            if h is None:
                continue
            if re.search(r"<!-- gstack-[a-z-]+-v\d+ -->", line):
                errors.append(f"E8 {gen}/SKILL.md:{i}: inline emitted-block copy (marker heading) — blocks/ is the single source")
            elif h in block_headings:
                errors.append(f"E8 {gen}/SKILL.md:{i}: inline emitted-block copy (markerless heading '{h}') — blocks/ is the single source")
        for ref in set(re.findall(r"blocks/([A-Za-z0-9_.-]+\.md)", text)):
            if not (blocks_dir / ref).is_file():
                errors.append(f"E8 {gen}/SKILL.md references nonexistent blocks/{ref}")

    # E12 placeholder completeness (2.48.0). PLACEHOLDERS.md's preamble says no
    # raw {{...}} token may reach a generated CLAUDE.md — but nothing checked
    # that a token a block introduces is documented anywhere a generator would
    # look. An undocumented one is emitted verbatim into a project's CLAUDE.md.
    if blocks_dir.is_dir():
        ph = blocks_dir / "PLACEHOLDERS.md"
        ph_text = ph.read_text() if ph.is_file() else ""
        documented = documented_placeholders(ph_text)
        # Named but empty: a heading with no body between it and the next heading.
        # Reported separately, because "you wrote the heading and stopped" is a
        # different mistake from "you never mentioned it".
        named = set(re.findall(r"^##\s+`\{\{([A-Z0-9_]+)\}\}`", ph_text, re.M))
        for f in sorted(blocks_dir.glob("*.md")):
            if f.name == "PLACEHOLDERS.md":
                continue
            for tok in sorted(set(re.findall(r"\{\{([A-Z0-9_]+)\}\}", f.read_text()))):
                if tok in documented:
                    continue
                how = ("has a heading in" if tok in named else "is not documented in")
                errors.append(
                    f"E12 {BLOCKS_DIR_REL}/{f.name}: placeholder {{{{{tok}}}}} {how} "
                    f"{BLOCKS_DIR_REL}/PLACEHOLDERS.md but no resolution rule under it — "
                    f"the generators have nothing to apply, so it reaches the project verbatim")

    # E9: no bare `/skill-name` for a THIS-PLUGIN skill inside blocks/. Blocks are
    # pasted verbatim into other projects, where `/htmlify` does not resolve —
    # only `/superpowers-gstack:htmlify` does. Scoped to blocks/ on purpose:
    # inside this repo's own SKILL.md files a bare name is merely sloppy, but in
    # an emitted block it is a dead reference in every project that adopts it.
    # gstack/Superpowers skills (/ship, /review, /investigate…) are correctly
    # bare and must NOT be flagged, so the name list comes from skills/ itself.
    if blocks_dir.is_dir():
        own = sorted((d.name for d in SKILLS.iterdir() if (d / "SKILL.md").is_file()),
                     key=len, reverse=True)
        if own:
            bare = bare_skill_ref_re(own)
            for f in sorted(blocks_dir.glob("*.md")):
                for i, line in enumerate(f.read_text().splitlines(), 1):
                    for m in bare.finditer(line):
                        errors.append(
                            f"E9 {BLOCKS_DIR_REL}/{f.name}:{i}: bare /{m.group(1)} in an emitted "
                            f"block — use /superpowers-gstack:{m.group(1)} (bare form does not "
                            f"resolve in the projects this block is pasted into)")

    # E11: the repo's own emitted-block region must be current. Hand-sync is what
    # let Session Continuity drift between the two generators for four releases —
    # this region is generated, so staleness is a build failure, not a hope.
    sync = REPO / "scripts" / "sync-own-claude-md.py"
    if sync.is_file():
        import importlib.util as _ilu
        _spec = _ilu.spec_from_file_location("sync_own_claude_md", sync)
        _mod = _ilu.module_from_spec(_spec)
        try:
            _spec.loader.exec_module(_mod)
            if _mod.splice(claude_md, _mod.render()) != claude_md:
                errors.append(
                    "E11 CLAUDE.md own-blocks region is stale — run "
                    "`python3 scripts/sync-own-claude-md.py`"
                )
        except Exception as exc:  # never let the guard itself break the lint
            warnings.append(f"W4 could not verify own-blocks region: {exc}")

    # E13 /adapt delegates to the script (3.1.0). The 2.9.0 -> 2.47.0
    # re-adaptation of sing-replay was correct on all nine markers and still
    # replaced a 198-line section with a 73-line block, destroying 125 lines of
    # project knowledge, unreported. The guards that make that visible are code
    # now (scripts/adapt-claude-md.py, tests/unit/test_adapt_script.py); this
    # rule keeps the skill from ever asking the model to do the merge again.
    adapt_skill = SKILLS / "adapt" / "SKILL.md"
    if adapt_skill.is_file():
        errors.extend(check_adapt_delegates(adapt_skill.read_text()))

    # E14 block files never carry the emitted= attribute (2.49.0). The count is a
    # fact about one emission, written by a generator into one project's CLAUDE.md.
    # Baked into the block file it becomes a constant that goes stale the next time
    # anyone edits the block — and a stale provenance number is worse than none,
    # because the growth check would trust it.
    if blocks_dir.is_dir():
        for f in sorted(blocks_dir.glob("*.md")):
            if "emitted=" in f.read_text().split("\n", 1)[0]:
                errors.append(
                    f"E14 {BLOCKS_DIR_REL}/{f.name}: line 1 carries `emitted=` — that "
                    f"attribute is written per-emission by the generators, never stored "
                    f"in the source block")

    for w in warnings:
        print(f"WARN  {w}")
    for e in errors:
        print(f"ERROR {e}")
    print(f"\nlint-skills: {len(errors)} error(s), {len(warnings)} warning(s) across {len(skill_dirs)} skills")
    return 1 if errors else 0


if __name__ == "__main__":
    sys.exit(main())
