#!/usr/bin/env python3
"""Lint the plugin's instruction surface (skills/, CLAUDE.md, README.md).

The 2026-07-03 system review found that 5 700 lines of SKILL.md had zero
validation — which is how a removed third-lens role kept shipping in generator
templates, three releases of work became unreachable by routing, and four
releases went out without CHANGELOG entries. This lint makes that whole drift
class impossible to reintroduce silently.

ERRORS (exit 1, CI-blocking):
  E1  SKILL.md frontmatter parses, `name` matches its directory, `description` present
  E2  cross-references resolve: `superpowers-gstack:<skill>` names and repo
      `scripts/<file>` paths mentioned in instruction files actually exist
  E3  routing coverage: every skill directory is mentioned in CLAUDE.md
  E4  plugin.json version has a matching `## [X.Y.Z]` entry in CHANGELOG.md
  E5  all `gstack-multi-lens-review-vN` markers carry the same N
  E6  no `version:` field in skill frontmatter (plugin.json is the version)
  E7  denylist: patterns that must never reappear in instruction files
      (e.g. the third-lens `sensitive` role removed in 2.18.0)
  E8  emitted blocks are single-sourced: every shared block file in
      skills/setup-routing/blocks/ exists, carries its version marker on the
      H2 heading line, and is referenced by BOTH generators (setup-routing,
      adapt); neither generator carries an inline copy (no marker heading in
      a SKILL.md). Replaced the old byte-identity drift guard in 2.33.0 —
      one source can't drift from itself.

  E10 upstream skill references resolve: every `superpowers:<name>` names a
      real Superpowers skill (roster: SUPERPOWERS_SKILLS). E2 only ever checked
      this plugin's OWN skill names, so an upstream name was unvalidated — the
      exact content the weekly auto-update job writes from release notes.

  E11 this repo's own CLAUDE.md carries a current copy of the universal blocks.
      check-plugin-version.sh exempts this repo from the /adapt nag (correctly —
      its CLAUDE.md is the SOURCE of the routing), but the exemption was wholesale,
      so the plugin prescribed discipline it never applied to itself. The region is
      generated by scripts/sync-own-claude-md.py; this fails when it goes stale.

  E12 every `{{TOKEN}}` used in a shared block has a NON-EMPTY resolution rule in
      blocks/PLACEHOLDERS.md. Without one the generators emit it verbatim into
      the project's CLAUDE.md — the exact outcome that file's preamble forbids.
      A heading alone does not count: `## `{{TOKEN}}`` with nothing under it
      documents nothing, and passed this rule until 2.48.0.

  E13 /adapt carries its content-loss guards — the pre-write snapshot, the real
      diff, the mandatory Removed report block, the growth check and the case-3
      attribution check — each inside the `### Step N` region that owns it, and
      in the right order within it. Each is prose that a reword could silently
      drop; the 2.47.0 field run showed the failure is invisible without them
      (skills/adapt/IMPROVEMENTS.md). Anchoring to the step is what makes the
      check real: bare substring needles left three of the four guards
      deletable with the lint still green.

  E14 no block file carries the `emitted=` marker attribute. Generators write that
      count into a project's CLAUDE.md at emit time; stored in the source it is a
      constant that goes stale on the next edit, and the growth check would trust it.

WARNINGS (reported, exit 0):
  W1  frontmatter description over budget (target <=30 words; hard cap comes
      with the Phase-3 description rewrites)
  W2  SKILL.md body over 500 lines (bloat radar)
  W3  SUPERPOWERS_SKILLS roster disagrees with the installed Superpowers plugin
      (maintainer machines only — CI has no upstream installed, so E10's roster
      is the CI-side source of truth and this is the drift alarm for it)

Run: python3 scripts/lint-skills.py   (from the repo root or anywhere)
"""
from __future__ import annotations

import json
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
SKILLS = REPO / "skills"
DESCRIPTION_WARN_WORDS = 30
BODY_WARN_LINES = 500

# Patterns that must never reappear in instruction files (skills/, CLAUDE.md,
# README.md — CHANGELOG is history and may mention them). Add an entry whenever
# a stale-reference class is purged, so it stays purged.
DENYLIST = [
    (re.compile(r"`sensitive`\s*="), "third-lens 'sensitive' role was removed in 2.18.0"),
    (re.compile(r"--role\s+sensitive|--sensitive\b"), "third-lens --sensitive flag was removed in 2.18.0"),
    (re.compile(r"gstack-multi-lens-review-v[0-4]\b"), "stale multi-lens marker (current: v5+)"),
    (re.compile(r"gstack-session-continuity-v[12]\b"), "stale session-continuity marker (current: v3+, 2.36.1)"),
    (re.compile(r"gstack-plan-fidelity-v1\b"), "stale plan-fidelity marker (current: v2+, 2.36.1)"),
    (re.compile(r"gstack-routing-v1\b"), "stale track-routing marker (current: v2+, 2.36.1)"),
    (re.compile(r"gstack-git-hygiene-v[0-8]\b"), "stale git-hygiene marker (current: v9+, 2.47.0)"),
    (re.compile(r"gstack-xcode-tools-v[0-5]\b"), "stale xcode-tools marker (current: v6+, 2.48.0)"),
    # v5 hardcoded `name=iPhone 16`; Xcode had already dropped it on the author's
    # own machine, and the resulting "Unable to find a device matching the
    # provided destination specifier" reads as a broken project, not a dead name.
    (re.compile(r"name=iPhone \d"),
     "hardcoded simulator model — use {{IOS_SIMULATOR}} or resolve by UDID (2.48.0)"),
    (re.compile(r"Pi \(local|Pi \(hybrid"), "local-model (Pi) routing columns removed in v0.2 (2.27.0)"),
    (re.compile(r"start-mlx"), "MLX local-server routing removed in v0.2 (2.27.0)"),
    (re.compile(r"models\.json"), "Pi models.json runtime detection removed in v0.2 (2.27.0)"),
    (re.compile(r"WXNUGGYB2B"), "hardcoded Apple Team ID removed in 2.33.0 — use the {{DEVELOPMENT_TEAM}} placeholder"),
    # Matches the usage form (with or without a subcommand). The lookahead
    # exempts prose that says the command does NOT exist ("there is no
    # `/cost-ledger` slash command").
    (re.compile(r"(?<![\w.~])/cost-ledger\b(?!`? slash command)"),
     "no /cost-ledger slash command exists — use python3 scripts/cost-ledger/cli.py <subcommand> (2.34.1)"),
    # 2.36.0: the handoff persistence mode was renamed auto -> continuous so it
    # stops colliding with Claude Code's `auto` PERMISSION mode (default for
    # Pro/Max/Team since 2026-08-14). Reading the legacy `mode: auto` value is
    # deliberate and stays legal — only these two purged forms are denied.
    (re.compile(r"auto context (guard|handoff)"),
     "renamed to 'continuous handoff' in 2.36.0 ('auto context guard' was also drifted wording in adapt)"),
    (re.compile(r"does not contain\s+`?##\s*Mode:\s*auto"),
     "marker-only compact sensor is stale — check YAML `mode:` (continuous, then legacy auto) first (2.36.0)"),
    # 2.48.0: Step 6 used to ask for a diff against a file Step 5 had already
    # overwritten. An unperformable verification is always answered
    # optimistically — the fix is a real snapshot, not better wording.
    (re.compile(r"diff the old vs new CLAUDE\.md mentally"),
     "unperformable verification — diff .gstack/CLAUDE.md.pre-adapt instead (2.48.0)"),
]

# Shared emitted blocks (skills/setup-routing/blocks/): single source for the
# sections both generators write into a project's CLAUDE.md. Marker-carrying
# blocks must have their `<!-- gstack-<name>-vN -->` marker on the H2 heading.
BLOCKS_DIR_REL = Path("skills") / "setup-routing" / "blocks"
MARKER_BLOCKS = [
    "autonomy.md",
    "git-hygiene.md",
    "multi-lens-review.md",
    "code-reuse.md",
    "plan-fidelity.md",
    "session-continuity.md",
    "track-routing.md",
    "xcode-tools.md",
    "companion-skills.md",
]
PLAIN_BLOCKS = ["model-routing-section.md", "PLACEHOLDERS.md"]

# E13: /adapt's content-loss guards. Each needle is a contract string, not a
# phrasing preference — the snapshot path a user restores from, the report label
# they grep for, the gate heading the per-section rules cross-reference.
#
# Each entry is anchored to the `### Step N` region that OWNS the guard, because
# a bare substring check proves only that the words occur somewhere in the file.
# Mutation-tested before this anchoring landed: deleting the whole Growth check
# gate left the lint GREEN, since the old needle `"**Growth check"` was also a
# substring of the 17 cross-references `Run the **Growth check** above`; deleting
# Step 6's mandatory diff item left it GREEN and the unit suite passing, which is
# the guard that FEEDS the Removed block; deleting the snapshot instruction left
# it GREEN because the path string survived at two other sites. A needle must
# prove the guard is in its own place, not that its words exist.
ADAPT_GUARDS = [
    ("Step 5", "cp CLAUDE.md .gstack/CLAUDE.md.pre-adapt",
     "the pre-write snapshot that gives Step 6 a real 'before' side"),
    ("Step 5", "are plugin-managed: /adapt replaces each one",
     "the CLAUDE.md header telling the user which sections are volatile"),
    ("Step 5", "**Growth check — applies to every marker-managed section",
     "the size gate itself, not one of its cross-references"),
    ("Step 5", "**Attribution check — applies to case 3",
     "the rule that refuses to replace a markerless section it cannot attribute"),
    ("Step 5", "sed -n '<start>,<end>p' CLAUDE.md",
     "the gate reads the LIVE file — pointing it at the snapshot applies live line "
     "numbers to a shifted file, and truncation only lowers the ratio, so it fails OPEN"),
    ("Step 6", "3. **Diff against the snapshot and classify every removed line.**",
     "the MANDATORY diff — the optional review's re-check runs only if the user says yes"),
    ("Step 6", "\n   diff .gstack/CLAUDE.md.pre-adapt CLAUDE.md\n",
     "the MANDATORY diff's own command, matched by its indented line rather than "
     "bare — the optional review below re-runs the same command inline, and a bare "
     "needle reported that copy after the mandatory one was deleted"),
    ("Step 6", "> **Removed (not plugin prose):**",
     "the only report block that can reveal a casualty — survivors lists cannot"),
    ("Step 6", ">   `Nothing project-authored was removed.`",
     "the sentinel that makes an empty Removed block mean 'checked', not 'skipped' — "
     "matched inside the report template, where it has to be written"),
    ("Step 6", "**Write the three block labels verbatim, in English",
     "the rule that keeps the three greppable labels out of the translation the rest "
     "of the report gets; it quotes the sentinel, which is what stopped the needle "
     "above from pinning the template"),
    ("Step 6", "> **Deferred (grown past its block, not upgraded):**",
     "the label that keeps a deferral (nothing lost) out of the block that means loss"),
    ("Step 5", "> `<heading>`: I cannot attribute this section to a past emitter",
     "the Attribution check's report line, which turns a two-sections-now-exist state "
     "into an actionable one"),
    ("Step 5", "> `Session Continuity`: I cannot attribute this section to a past emitter",
     "the same report for Session Continuity's own handoff.md sniff test, which reaches "
     "the identical preserve-and-insert state by a different route"),
    ("Step 5", "When you write a block into CLAUDE.md, add a SECOND HTML",
     "the imperative that makes provenance exist at all — weakened to 'you MAY add' "
     "or deleted outright, every other guard on this branch still passes while no "
     "generator writes an `emitted=` for them to check"),
    ("Step 5", "do not estimate it and do not carry a stale value forward",
     "the only textual guard on the replace path against a stale `emitted=` riding "
     "onto a new marker — a wrong `<N>` inside the sanity band silences the trigger "
     "for that section"),
    ("Step 5", "**Provenance (measured, not inferred).**",
     "the trigger that reads what the plugin actually wrote, not a ratio against a moving block"),
    ("Step 5", "append the provenance comment after it",
     "the heading-level rule's own provenance write — it calls itself the general rule "
     "for every marker-managed section, and 'copy the marker from the block' cannot "
     "produce an `emitted=` a block file never carries"),
    ("Step 5", "**Distrust an implausible `<N>`.**",
     "the sanity check on a count nothing verifies — without it one wrong number "
     "silences the gate for that section"),
    ("Step 5", "it adds a\nreason to stop; it never removes one",
     "the precedence rule: provenance may only ever ADD a reason to stop, so a bad "
     "`<N>` cannot switch off the two proxies that would still have caught the growth"),
]

# E13 ordering: a guard in the right step but the wrong place is still broken.
# (region, earlier, later, why)
ADAPT_GUARD_ORDER = [
    ("Step 5", "cp CLAUDE.md .gstack/CLAUDE.md.pre-adapt",
     "**Growth check — applies to every marker-managed section",
     "the snapshot must be written before anything reads a 'before' state"),
    ("Step 6", "3. **Diff against the snapshot and classify every removed line.**",
     "**STOP HERE.**",
     "the mandatory diff must sit above the optional-review gate — below it, a user "
     "who declines the review never gets the classification the Removed block needs"),
]

errors: list[str] = []
warnings: list[str] = []


def heading_text(line: str) -> str | None:
    """Normalized heading text for E8's inline-copy guard, or None if `line` is
    not a heading at all.

    A re-paste of an emitted block can wear several disguises, and each one that
    slips through reopens the drift class E8 exists to close. This tolerates:
    leading whitespace (the pre-2.36.0 Session Continuity copy hid indented
    inside a fenced example and sailed past a bare startswith("#") for four
    releases), blockquote/list prefixes, ATX closing hashes, the gstack version
    marker, and letter case. Body-only copies with no heading remain out of
    reach — a heading-keyed check cannot see them, and the CHANGELOG says so.
    """
    # Blockquote markers and whitespace strip unconditionally. A list marker
    # strips only in its real form (`- `, `* `, `+ ` with trailing space) — a
    # blanket [-*+]* class would also eat a `---` rule or a hyphenated token and
    # expose a following `#`, inventing a false-positive class that the older
    # startswith("#") check did not have (third-lens P3, 2.36.0).
    s = re.sub(r"^[\s>]*", "", line)
    s = re.sub(r"^[-*+][ \t]+", "", s)
    if not s.startswith("#"):
        return None
    s = s.lstrip("#").strip()
    s = re.sub(r"\s*<!-- gstack-[a-z-]+-v\d+ -->\s*$", "", s)
    return re.sub(r"\s*#+$", "", s).strip().lower()


def documented_placeholders(text: str) -> set[str]:
    """Tokens that PLACEHOLDERS.md actually documents (E12).

    Heading membership is not documentation. `## \\`{{TOKEN}}\\`` followed
    immediately by the next heading names a placeholder and gives the generator
    nothing to resolve it with, which is the same outcome as no entry at all —
    a raw `{{TOKEN}}` in the project's CLAUDE.md. E12 accepted exactly that
    until 2.48.0, and so did its unit test.
    """
    out: set[str] = set()
    heads = list(re.finditer(r"^##\s+`\{\{([A-Z0-9_]+)\}\}`.*$", text, re.M))
    for i, m in enumerate(heads):
        nxt = re.search(r"^#{1,6} ", text[m.end():], re.M)
        end = m.end() + nxt.start() if nxt else len(text)
        if text[m.end():end].strip():
            out.add(m.group(1))
    return out


def step_regions(text: str) -> dict[str, str]:
    """Split an instruction file into its `### Step N` regions.

    E13's anchor. A guard's needle has to be found inside the step that owns it —
    `**Growth check` matched 17 cross-references elsewhere in the file, so the
    gate could be deleted outright with the lint still green.
    """
    marks = [(m.start(), m.group(1)) for m in re.finditer(r"^### (Step \d+)\b", text, re.M)]
    regions: dict[str, str] = {}
    for i, (pos, name) in enumerate(marks):
        end = marks[i + 1][0] if i + 1 < len(marks) else len(text)
        regions[name] = text[pos:end]
    return regions


def check_adapt_guards(text: str) -> list[str]:
    """E13: /adapt's content-loss guards, each in the step that owns it.

    Returns the error strings rather than appending to the module-level list, so
    the unit suite can mutate the skill text in memory and prove each guard's
    deletion turns the lint red — the property the guards claim and did not have.
    """
    errs: list[str] = []
    regions = step_regions(text)
    for step in sorted({s for s, _, _ in ADAPT_GUARDS} - set(regions)):
        errs.append(
            f"E13 adapt/SKILL.md has no `### {step}` heading — the content-loss "
            f"guards anchored to it cannot be located, so nothing pins them")
    for step, needle, why in ADAPT_GUARDS:
        region = regions.get(step)
        if region is None:
            continue
        hits = region.count(needle)
        if hits == 0:
            errs.append(
                f"E13 adapt/SKILL.md: {step} is missing content-loss guard "
                f"{needle!r} — {why}")
        elif hits > 1:
            # A needle matching twice reports the copy, not the site it names:
            # delete the guard and the other occurrence keeps the lint green.
            # Three needles were in exactly that state at 2.49.0 — two of them
            # put there by the very branch that reviewed them — and each was
            # found by deleting an occurrence, never by reading.
            errs.append(
                f"E13 adapt/SKILL.md: {step} matches content-loss guard {needle!r} "
                f"{hits} times, so it no longer pins {why} — deleting that guard "
                f"would leave the lint green on the other copy. Re-point the needle "
                f"at something unique to its own site")
    for step, first, second, why in ADAPT_GUARD_ORDER:
        region = regions.get(step)
        if not region:
            # NOT already reported above: that loop only scans steps ADAPT_GUARDS
            # names, so a step appearing solely in ADAPT_GUARD_ORDER is invisible
            # to it — this has to say so itself, or extending the ordering list
            # with a new step is a silent no-op the day it isn't also in ADAPT_GUARDS.
            errs.append(
                f"E13 adapt/SKILL.md: ordering rule names {step!r}, which has no "
                f"`### {step}` heading — the rule cannot run, so it is reporting "
                f"nothing rather than passing")
            continue
        if first not in region:
            errs.append(
                f"E13 adapt/SKILL.md: {step}'s ordering anchor {first!r} is gone — "
                f"the order check cannot run, so it is reporting nothing rather "
                f"than passing")
        elif second not in region:
            errs.append(
                f"E13 adapt/SKILL.md: {step}'s ordering anchor {second!r} is gone — "
                f"the order check cannot run, so it is reporting nothing rather "
                f"than passing")
        elif region.index(first) > region.index(second):
            errs.append(
                f"E13 adapt/SKILL.md: in {step}, {first!r} appears after "
                f"{second!r} — {why}")
    return errs


def bare_skill_ref_re(own_skill_names) -> "re.Pattern":
    r"""Match a bare `/skill-name` for a skill THIS plugin owns (E9).

    The boundaries do the work. Both sides must be guarded:
      `/superpowers-gstack:htmlify`  namespaced — holds no `/htmlify` substring,
                                     so it never matches in the first place
      `skills/htmlify/SKILL.md`      a path — word char before the slash
      `./htmlify/SKILL.md`           a path — trailing `/` after the name
      `/e2e-route-extra`             a longer token — trailing `-` after the name
      `/ship`, `/review`             gstack/Superpowers skills, correctly bare —
                                     excluded by not being in `own_skill_names`
    `:` is deliberately NOT in the lookbehind: it cannot protect the namespaced
    form (no `/name` there to match) and only creates misses like `label:/htmlify`.
    A trailing `\b` alone is not enough — it accepts `-` and `/`, which is how
    both false-positive classes got in. Longest-first alternation so `/e2e-route`
    is never reported as `/e2e`.
    """
    names = sorted(own_skill_names, key=len, reverse=True)
    return re.compile(r"(?<![\w/-])/(" + "|".join(map(re.escape, names)) + r")(?![\w/-])")


def frontmatter(text: str) -> dict | None:
    """Minimal YAML-ish frontmatter reader: top-level `key:` lines between --- markers.
    Values are not fully parsed (multi-line descriptions concatenate); enough for linting."""
    m = re.match(r"\A---\n(.*?)\n---\n", text, re.DOTALL)
    if not m:
        return None
    fm: dict[str, str] = {}
    key = None
    for line in m.group(1).splitlines():
        km = re.match(r"^([A-Za-z_-]+):\s*(.*)$", line)
        if km:
            key = km.group(1)
            val = km.group(2).strip()
            # A bare block-scalar indicator (|, >, with optional chomping) is not
            # content — the value is on the following indented lines. Counting the
            # `|` as a word would over-count every block-scalar description by one.
            fm[key] = "" if val in ("|", ">", "|-", "|+", ">-", ">+") else val
        elif key and (line.startswith("  ") or line.startswith("\t")):
            fm[key] = (fm[key] + " " + line.strip()).strip()
    return fm


# Upstream skills this plugin is allowed to route to (E10). Checked in rather
# than read from disk because CI has no upstream installed — a disk-only check
# would be silent exactly where it matters, on the auto-update PR.
#
# Scoped to Superpowers on purpose. gstack ships ~50 skills on a weekly cadence;
# a checked-in list that large would drift faster than it protects, and its bare
# `/name` form collides with E9's own-skill matcher. Superpowers is 14 names on a
# slow cadence, and the namespaced `superpowers:<name>` form is unambiguous.
SUPERPOWERS_SKILLS = {
    "brainstorming",
    "dispatching-parallel-agents",
    "executing-plans",
    "finishing-a-development-branch",
    "receiving-code-review",
    "requesting-code-review",
    "subagent-driven-development",
    "systematic-debugging",
    "test-driven-development",
    "using-git-worktrees",
    "using-superpowers",
    "verification-before-completion",
    "writing-plans",
    "writing-skills",
}
SUPERPOWERS_CACHE_GLOB = "plugins/cache/claude-plugins-official/superpowers/*/skills"


def installed_superpowers_skills():
    """Skill names from the newest installed Superpowers, or None if absent.

    Absent is the normal case in CI. Returning None (not an empty set) keeps the
    caller from reading "not installed" as "upstream has no skills".
    """
    dirs = sorted((Path.home() / ".claude").glob(SUPERPOWERS_CACHE_GLOB))
    if not dirs:
        return None
    newest = dirs[-1]
    return {d.name for d in newest.iterdir() if (d / "SKILL.md").is_file()}


def check_upstream_skills(path: Path, text: str) -> None:
    """E10: `superpowers:<name>` references must name a real upstream skill.

    E2 validates only THIS plugin's own skill names, so an upstream name was
    unvalidated everywhere. That is precisely the content the weekly auto-update
    job generates from release notes — a hallucinated skill would have passed
    every gate and shipped a dead routing row into every generated CLAUDE.md.
    """
    for name in set(re.findall(r"(?<!-)superpowers:([a-z0-9-]+)", text)):
        if name not in SUPERPOWERS_SKILLS:
            errors.append(
                f"E10 {path.relative_to(REPO)}: reference to unknown upstream skill "
                f"'superpowers:{name}' — not in SUPERPOWERS_SKILLS. If upstream really "
                f"added it, verify against the installed plugin and add it to the roster."
            )


def check_refs(path: Path, text: str, repo_doc: bool) -> None:
    """E2: skill-name and repo-script references must resolve.

    Path semantics learned on the lint's first run: a bare `scripts/<x>` inside a
    SKILL.md body is a USER-project path by convention (scaffolds emit
    scripts/run-uitests.sh into the target project; generated CLAUDE.md rows name
    project scripts). Repo assets are referenced via `$SKILL_DIR/../../scripts/<x>`
    — those must resolve. In repo docs (CLAUDE.md, README) bare `scripts/` refs
    mean this repo and are checked too."""
    for name in set(re.findall(r"superpowers-gstack:([a-z0-9-]+)", text)):
        if not (SKILLS / name).is_dir():
            errors.append(f"E2 {path.relative_to(REPO)}: reference to nonexistent skill 'superpowers-gstack:{name}'")
    for line in text.splitlines():
        # skip external-path lines (gstack's own skills/bin live under ~/.claude)
        if ".claude/skills" in line or "gstack/bin" in line:
            continue
        for script in set(re.findall(r"\$SKILL_DIR/\.\./\.\./scripts/([A-Za-z0-9_.-]+)", line)):
            if not (REPO / "scripts" / script).exists():
                errors.append(f"E2 {path.relative_to(REPO)}: repo-asset reference to nonexistent 'scripts/{script}'")
        if repo_doc:
            for script in set(re.findall(r"(?<![\w/.])scripts/([A-Za-z0-9_.-]+)", line)):
                if not (REPO / "scripts" / script).exists():
                    errors.append(f"E2 {path.relative_to(REPO)}: reference to nonexistent script 'scripts/{script}'")


def main() -> int:
    skill_dirs = sorted(d for d in SKILLS.iterdir() if d.is_dir())
    claude_md = (REPO / "CLAUDE.md").read_text()
    readme = (REPO / "README.md").read_text()

    # E1 + E6 + W1 + W2 per skill
    for d in skill_dirs:
        skill_md = d / "SKILL.md"
        if not skill_md.is_file():
            errors.append(f"E1 {d.name}: missing SKILL.md")
            continue
        text = skill_md.read_text()
        fm = frontmatter(text)
        if fm is None:
            errors.append(f"E1 {d.name}: no frontmatter block")
            continue
        if fm.get("name") != d.name:
            errors.append(f"E1 {d.name}: frontmatter name '{fm.get('name')}' != directory name")
        desc = fm.get("description", "")
        if not desc:
            errors.append(f"E1 {d.name}: missing/empty description")
        elif len(desc.split()) > DESCRIPTION_WARN_WORDS:
            warnings.append(f"W1 {d.name}: description is {len(desc.split())} words (target <=30 — per-session tax in every project)")
        if "version" in fm:
            errors.append(f"E6 {d.name}: frontmatter 'version:' field — plugin.json is the only version")
        if text.count("\n") > BODY_WARN_LINES:
            warnings.append(f"W2 {d.name}: SKILL.md body is {text.count(chr(10))} lines (>500 — bloat radar)")
        check_refs(skill_md, text, repo_doc=False)
        check_upstream_skills(skill_md, text)

    # E2 on CLAUDE.md + README too
    check_refs(REPO / "CLAUDE.md", claude_md, repo_doc=True)
    check_upstream_skills(REPO / "CLAUDE.md", claude_md)
    check_refs(REPO / "README.md", readme, repo_doc=True)
    check_upstream_skills(REPO / "README.md", readme)

    # E10 layer 2: the roster itself must match reality. Only runs where an
    # upstream is installed (never in CI), so it catches roster drift on a
    # maintainer's machine without making CI depend on a local install.
    _installed = installed_superpowers_skills()
    if _installed is not None:
        for missing in sorted(_installed - SUPERPOWERS_SKILLS):
            warnings.append(f"W3 SUPERPOWERS_SKILLS is missing '{missing}' — installed upstream has it; add it to the roster")
        for phantom in sorted(SUPERPOWERS_SKILLS - _installed):
            warnings.append(f"W3 SUPERPOWERS_SKILLS lists '{phantom}' — installed upstream does NOT have it; verify before routing to it")


    # E3 routing coverage
    for d in skill_dirs:
        if d.name not in claude_md:
            errors.append(f"E3 CLAUDE.md: skill '{d.name}' has no mention — unreachable by routing")

    # E4 version <-> CHANGELOG
    version = json.loads((REPO / ".claude-plugin" / "plugin.json").read_text())["version"]
    if f"## [{version}]" not in (REPO / "CHANGELOG.md").read_text():
        errors.append(f"E4 CHANGELOG.md: no entry for plugin.json version {version} — ship-worthy releases require a CHANGELOG entry")

    # E5 multi-lens marker consistency (SKILL.md files + shared block files)
    marker_versions = set()
    marker_files = [d / "SKILL.md" for d in skill_dirs]
    marker_files += sorted((REPO / BLOCKS_DIR_REL).glob("*.md")) if (REPO / BLOCKS_DIR_REL).is_dir() else []
    for f in marker_files:
        for m in re.finditer(r"gstack-multi-lens-review-v(\d+)", f.read_text()):
            marker_versions.add(m.group(1))
    if len(marker_versions) > 1:
        errors.append(f"E5 multi-lens markers disagree across skills: v{sorted(marker_versions)}")

    # E7 denylist
    targets = [(REPO / "CLAUDE.md", claude_md), (REPO / "README.md", readme)]
    targets += [(d / "SKILL.md", (d / "SKILL.md").read_text()) for d in skill_dirs if (d / "SKILL.md").is_file()]
    # Also scan the canonical routing table — the file most likely to regress a
    # purged local-model (Pi/MLX) pattern, yet it is not a SKILL.md.
    _mr = REPO / "skills" / "setup-routing" / "model-routing.md"
    if _mr.is_file():
        targets.append((_mr, _mr.read_text()))
    # ... and the shared emitted blocks — they ARE the generated-CLAUDE.md content.
    if (REPO / BLOCKS_DIR_REL).is_dir():
        targets += [(f, f.read_text()) for f in sorted((REPO / BLOCKS_DIR_REL).glob("*.md"))]
    # ... and the scripts themselves — user-facing messages/docstrings drift the
    # same way instruction files do (the 2.34.1 audit found `/cost-ledger pause`
    # in cli.py output after the .md sweep missed it). lint-skills.py itself is
    # exempt: it carries the patterns by definition.
    targets += [(f, f.read_text()) for pat in ("*.py", "*.sh")
                for f in sorted((REPO / "scripts").rglob(pat))
                if f.name != "lint-skills.py" and "__pycache__" not in f.parts]
    for path, text in targets:
        for pattern, why in DENYLIST:
            for i, line in enumerate(text.splitlines(), 1):
                if pattern.search(line):
                    errors.append(f"E7 {path.relative_to(REPO)}:{i}: denylisted pattern ({why})")

    # E8 single-source guard for emitted blocks (2.33.0, replaces the old
    # byte-identity drift check — one source can't drift from itself):
    #   (a) every shared block file exists;
    #   (b) marker blocks carry `<!-- gstack-<x>-vN -->` on their H2 heading line;
    #   (c) BOTH generators reference every block filename (no orphaned block,
    #       no generator that forgot to emit one);
    #   (d) NEITHER generator has an inline copy — a heading line carrying a
    #       gstack marker inside a SKILL.md is a regression to hand-maintained
    #       duplication (the class the 2.27.0 pre-merge review caught).
    blocks_dir = REPO / BLOCKS_DIR_REL
    gen_texts = {name: (SKILLS / name / "SKILL.md").read_text()
                 for name in ("setup-routing", "adapt")
                 if (SKILLS / name / "SKILL.md").is_file()}
    for fname in MARKER_BLOCKS + PLAIN_BLOCKS:
        f = blocks_dir / fname
        if not f.is_file():
            errors.append(f"E8 missing shared block file {BLOCKS_DIR_REL}/{fname}")
            continue
        if fname in MARKER_BLOCKS:
            first = f.read_text().split("\n", 1)[0]
            if not re.match(r"^## .*<!-- gstack-[a-z-]+-v\d+ -->$", first):
                errors.append(f"E8 {BLOCKS_DIR_REL}/{fname}: first line must be an H2 heading with a gstack version marker")
        # PLACEHOLDERS.md included: a generator that stops referencing it could
        # emit raw {{...}} tokens into a project's CLAUDE.md.
        for gen, text in gen_texts.items():
            if fname not in text:
                errors.append(f"E8 {gen}/SKILL.md never references blocks/{fname} — generator would not emit/resolve it")
    if (blocks_dir / "model-routing-section.md").is_file():
        if "## Model Routing" not in (blocks_dir / "model-routing-section.md").read_text():
            errors.append("E8 blocks/model-routing-section.md lost its `## Model Routing` anchor")
    # Orphan guard: a blocks/*.md not in the known lists has no emitter — it
    # would silently never reach any generated CLAUDE.md.
    if blocks_dir.is_dir():
        for f in sorted(blocks_dir.glob("*.md")):
            if f.name not in MARKER_BLOCKS + PLAIN_BLOCKS:
                errors.append(f"E8 orphaned block file {BLOCKS_DIR_REL}/{f.name} — not in MARKER_BLOCKS/PLAIN_BLOCKS, no generator emits it")
    # Inline copies are forbidden WITH or WITHOUT the marker — a markerless
    # re-paste of a block heading would reopen the drift class E8 exists to
    # prevent (Codex P2 on the 2.33.0 branch caught exactly this hole).
    block_headings = set()
    for fname in MARKER_BLOCKS + ["model-routing-section.md"]:
        f = blocks_dir / fname
        if f.is_file():
            h = heading_text(f.read_text().split("\n", 1)[0])
            if h:
                block_headings.add(h)
    for gen, text in gen_texts.items():
        for i, line in enumerate(text.splitlines(), 1):
            h = heading_text(line)
            if h is None:
                continue
            if re.search(r"<!-- gstack-[a-z-]+-v\d+ -->", line):
                errors.append(f"E8 {gen}/SKILL.md:{i}: inline emitted-block copy (marker heading) — blocks/ is the single source")
            elif h in block_headings:
                errors.append(f"E8 {gen}/SKILL.md:{i}: inline emitted-block copy (markerless heading '{h}') — blocks/ is the single source")
        for ref in set(re.findall(r"blocks/([A-Za-z0-9_.-]+\.md)", text)):
            if not (blocks_dir / ref).is_file():
                errors.append(f"E8 {gen}/SKILL.md references nonexistent blocks/{ref}")

    # E12 placeholder completeness (2.48.0). PLACEHOLDERS.md's preamble says no
    # raw {{...}} token may reach a generated CLAUDE.md — but nothing checked
    # that a token a block introduces is documented anywhere a generator would
    # look. An undocumented one is emitted verbatim into a project's CLAUDE.md.
    if blocks_dir.is_dir():
        ph = blocks_dir / "PLACEHOLDERS.md"
        ph_text = ph.read_text() if ph.is_file() else ""
        documented = documented_placeholders(ph_text)
        # Named but empty: a heading with no body between it and the next heading.
        # Reported separately, because "you wrote the heading and stopped" is a
        # different mistake from "you never mentioned it".
        named = set(re.findall(r"^##\s+`\{\{([A-Z0-9_]+)\}\}`", ph_text, re.M))
        for f in sorted(blocks_dir.glob("*.md")):
            if f.name == "PLACEHOLDERS.md":
                continue
            for tok in sorted(set(re.findall(r"\{\{([A-Z0-9_]+)\}\}", f.read_text()))):
                if tok in documented:
                    continue
                how = ("has a heading in" if tok in named else "is not documented in")
                errors.append(
                    f"E12 {BLOCKS_DIR_REL}/{f.name}: placeholder {{{{{tok}}}}} {how} "
                    f"{BLOCKS_DIR_REL}/PLACEHOLDERS.md but no resolution rule under it — "
                    f"the generators have nothing to apply, so it reaches the project verbatim")

    # E9: no bare `/skill-name` for a THIS-PLUGIN skill inside blocks/. Blocks are
    # pasted verbatim into other projects, where `/htmlify` does not resolve —
    # only `/superpowers-gstack:htmlify` does. Scoped to blocks/ on purpose:
    # inside this repo's own SKILL.md files a bare name is merely sloppy, but in
    # an emitted block it is a dead reference in every project that adopts it.
    # gstack/Superpowers skills (/ship, /review, /investigate…) are correctly
    # bare and must NOT be flagged, so the name list comes from skills/ itself.
    if blocks_dir.is_dir():
        own = sorted((d.name for d in SKILLS.iterdir() if (d / "SKILL.md").is_file()),
                     key=len, reverse=True)
        if own:
            bare = bare_skill_ref_re(own)
            for f in sorted(blocks_dir.glob("*.md")):
                for i, line in enumerate(f.read_text().splitlines(), 1):
                    for m in bare.finditer(line):
                        errors.append(
                            f"E9 {BLOCKS_DIR_REL}/{f.name}:{i}: bare /{m.group(1)} in an emitted "
                            f"block — use /superpowers-gstack:{m.group(1)} (bare form does not "
                            f"resolve in the projects this block is pasted into)")

    # E11: the repo's own emitted-block region must be current. Hand-sync is what
    # let Session Continuity drift between the two generators for four releases —
    # this region is generated, so staleness is a build failure, not a hope.
    sync = REPO / "scripts" / "sync-own-claude-md.py"
    if sync.is_file():
        import importlib.util as _ilu
        _spec = _ilu.spec_from_file_location("sync_own_claude_md", sync)
        _mod = _ilu.module_from_spec(_spec)
        try:
            _spec.loader.exec_module(_mod)
            if _mod.splice(claude_md, _mod.render()) != claude_md:
                errors.append(
                    "E11 CLAUDE.md own-blocks region is stale — run "
                    "`python3 scripts/sync-own-claude-md.py`"
                )
        except Exception as exc:  # never let the guard itself break the lint
            warnings.append(f"W4 could not verify own-blocks region: {exc}")

    # E13 /adapt content-loss guards (2.48.0). The 2.9.0 -> 2.47.0 re-adaptation
    # of sing-replay was correct on all nine markers and still replaced a
    # 198-line section with a 73-line block, destroying 125 lines of project
    # knowledge, unreported. These guards are the mechanism that makes that
    # visible; they are prose, so nothing but a lint keeps them from being
    # reworded away.
    adapt_skill = SKILLS / "adapt" / "SKILL.md"
    if adapt_skill.is_file():
        errors.extend(check_adapt_guards(adapt_skill.read_text()))

    # E14 block files never carry the emitted= attribute (2.49.0). The count is a
    # fact about one emission, written by a generator into one project's CLAUDE.md.
    # Baked into the block file it becomes a constant that goes stale the next time
    # anyone edits the block — and a stale provenance number is worse than none,
    # because the growth check would trust it.
    if blocks_dir.is_dir():
        for f in sorted(blocks_dir.glob("*.md")):
            if "emitted=" in f.read_text().split("\n", 1)[0]:
                errors.append(
                    f"E14 {BLOCKS_DIR_REL}/{f.name}: line 1 carries `emitted=` — that "
                    f"attribute is written per-emission by the generators, never stored "
                    f"in the source block")

    for w in warnings:
        print(f"WARN  {w}")
    for e in errors:
        print(f"ERROR {e}")
    print(f"\nlint-skills: {len(errors)} error(s), {len(warnings)} warning(s) across {len(skill_dirs)} skills")
    return 1 if errors else 0


if __name__ == "__main__":
    sys.exit(main())
