#!/usr/bin/env python3
"""Emit this repo's own copy of the universal blocks into its CLAUDE.md.

The gap this closes: `check-plugin-version.sh` exempts this repo from the /adapt
nag — correctly, since its CLAUDE.md is the source of the routing and carries no
generated marker. But the exemption is wholesale, so every block shipped to user
projects never applied to the repo producing them. The plugin prescribed discipline
it did not practise, and had six stranded branches to show for it (2026-08-18).

Rejected alternatives:
  * Run /adapt on this repo — would stamp a version marker, making the
    version-check hook nag here forever and putting the repo's routing (the
    SOURCE) under generated management. Backwards.
  * Hand-sync with a "keep in sync" comment — the exact mechanism that let
    Session Continuity drift between the two generators for four releases.
So: generate, and let E11 fail the build when the region goes stale.

Only genuinely universal blocks are emitted. track-routing/xcode-tools/
companion-skills are native-track conditional and meaningless for a plugin repo;
model-routing-section carries an unresolved {{DOMAIN_SENSITIVITY}} placeholder.

Usage: python3 scripts/sync-own-claude-md.py [--check]
"""
from __future__ import annotations
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
BLOCKS = REPO / "skills" / "setup-routing" / "blocks"
CLAUDE_MD = REPO / "CLAUDE.md"

UNIVERSAL = [
    "autonomy.md",
    "git-hygiene.md",
    "multi-lens-review.md",
    "code-reuse.md",
    "plan-fidelity.md",
    "session-continuity.md",
]

def emitted_heading(raw: str) -> str:
    """The block's first line as a GENERATOR writes it into a project's CLAUDE.md.

    /adapt and setup-routing append a second HTML comment carrying the block's
    line count — `<!-- gstack-git-hygiene-v9 --><!-- emitted=162 -->` — beside the
    marker, never inside it, so every reader that knows only the bare marker keeps
    matching. Doing the same here is what keeps this region's claim true: what
    this repo follows is what /adapt emits elsewhere, provenance included.

    `<N>` is `wc -l` of the block file, i.e. its newline count — the same
    definition the generators are given, in executable form.
    """
    head, _, rest = raw.rstrip("\n").partition("\n")
    return f"{head}<!-- emitted={raw.count(chr(10))} -->\n{rest}"


BEGIN = "<!-- BEGIN own-blocks — generated by scripts/sync-own-claude-md.py; do not edit by hand -->"
END = "<!-- END own-blocks -->"


def render() -> str:
    parts = [
        BEGIN,
        "",
        # "the blocks are byte-identical" was true until 2.49.0, when this script
        # started rewriting every heading to append provenance. The BODY is what
        # is byte-identical; the heading carries one comment the block file does
        # not. Do not write a literal HTML comment terminator in here — this text
        # IS an HTML comment, and comments do not nest.
        "<!-- This repo eats its own dog food: each block's BODY below is byte-identical",
        "     to what /adapt emits into every other project, and each heading carries the",
        "     same `emitted=` provenance comment a generator appends beside the marker.",
        "     Regenerate with `python3 scripts/sync-own-claude-md.py`; lint rule E11",
        "     fails if stale. -->",
        "",
    ]
    for name in UNIVERSAL:
        parts.append(emitted_heading((BLOCKS / name).read_text()))
        parts.append("")
    parts.append(END)
    return "\n".join(parts) + "\n"


def splice(text: str, region: str) -> str:
    if BEGIN in text and END in text:
        head = text[: text.index(BEGIN)]
        tail = text[text.index(END) + len(END):].lstrip("\n")
        return head + region + ("\n" + tail if tail else "")
    return text.rstrip("\n") + "\n\n" + region


def main() -> int:
    check = "--check" in sys.argv
    current = CLAUDE_MD.read_text()
    wanted = splice(current, render())
    if current == wanted:
        print("own-blocks: up to date")
        return 0
    if check:
        print("own-blocks: STALE — run `python3 scripts/sync-own-claude-md.py`", file=sys.stderr)
        return 1
    CLAUDE_MD.write_text(wanted)
    print(f"own-blocks: synced {len(UNIVERSAL)} blocks into CLAUDE.md")
    return 0


if __name__ == "__main__":
    sys.exit(main())
