"""Guard the `.gstack/e2e-executor` axis — the one pin that can lie quietly.

Every other failure in this feature announces itself: a VM that will not boot, a rig
that is not installed, a test that fails. The dangerous one is a run that looks
completely normal while executing somewhere the user did not choose — a `VM` typo
degrading to host, or every test skipped and exit 0.

So these tests hold three properties: the pin is validated rather than coerced, an
absent rig and a failing rig get opposite treatment, and `executed` is always visible.
They assert on SKILL.md prose the way test_spec_drift_skill.py does, because these
contracts live in text an agent reads, plus real behaviour for the shell that ships.
"""
from __future__ import annotations

import os
import re
import subprocess
import sys
import tempfile
from pathlib import Path

import pytest

REPO = Path(__file__).resolve().parents[2]
ROUTE = (REPO / "skills" / "e2e-route" / "SKILL.md").read_text()
SCAFFOLD = (REPO / "skills" / "macos-e2e-scaffold" / "SKILL.md").read_text()
XCODE_BLOCK = (REPO / "skills" / "setup-routing" / "blocks" / "xcode-tools.md").read_text()
PLACEHOLDERS = (REPO / "skills" / "setup-routing" / "blocks" / "PLACEHOLDERS.md").read_text()
ADAPT = (REPO / "skills" / "adapt" / "SKILL.md").read_text()
SETUP = (REPO / "skills" / "setup-routing" / "SKILL.md").read_text()
HYGIENE = REPO / "scripts" / "vm-hygiene.sh"


def runner_template() -> str:
    """The generated scripts/run-uitests.sh, as it sits in the scaffold skill.

    Anchor on the VERSIONED banner: the SPM-only stub earlier in the file starts with
    the same unversioned prefix, and matching that returns a four-line refusal instead
    of the runner — every assertion below would then pass or fail for the wrong reason.
    """
    start = SCAFFOLD.index("# Auto-generated by /macos-e2e-scaffold v")
    return SCAFFOLD[start:SCAFFOLD.index("```", start)]


def flat(text: str) -> str:
    """Whitespace-collapsed, so an assertion does not depend on where prose wrapped."""
    return " ".join(text.split())


# --- the pin is validated, never coerced ------------------------------------------

# Explicit ids: the parameters here are whole SKILL.md files, and pytest would otherwise
# derive multi-thousand-character node ids from them, put those in PYTEST_CURRENT_TEST,
# and hand every spawned subprocess an oversized environment — E2BIG on Linux, fine on
# macOS. That is the 2.52.1 bug; test_node_id_budget.py caught this very test.
@pytest.mark.parametrize("surface,text", [
    pytest.param("runner template", runner_template(), id="runner-template"),
    pytest.param("e2e-route", ROUTE, id="e2e-route"),
    pytest.param("xcode-tools block", XCODE_BLOCK, id="xcode-tools-block"),
    pytest.param("PLACEHOLDERS", PLACEHOLDERS, id="placeholders"),
])
def test_an_invalid_pin_is_refused_not_treated_as_host(surface, text):
    """`VM`, a trailing space or a stray comment must not degrade to host. Coercing an
    unrecognised value is indistinguishable from success at the point it matters."""
    assert "BLOCKED — invalid .gstack/e2e-executor" in flat(text), surface


def test_absence_of_the_file_means_host_everywhere():
    """The default is defined, not incidental — a project that never opts in must read
    correctly rather than hit an error path."""
    for surface, text in (("route", ROUTE), ("block", XCODE_BLOCK), ("placeholders", PLACEHOLDERS)):
        assert re.search(r"absen\w+ (of the file )?means?\s+`?host`?|file's absence means", text), surface


# --- absent rig and failing rig are opposites -------------------------------------

def test_missing_rig_falls_back_loudly():
    template = runner_template()
    assert "rig not found on this host — running on host without lease" in template
    assert "rig not found on this host — running on host without lease" in ROUTE, \
        "the route's decision block must carry the same wording the runner prints"


def test_a_failing_rig_does_not_fall_back():
    """The distinction the whole design turns on: a rig FAULT is the thing to surface.
    Running on the host instead converts a real defect into a silently slower pass."""
    template = runner_template()
    assert "E2E RIG FAILED" in template
    assert "Not falling back to the host" in template
    fault = template.index("E2E RIG FAILED")
    fallback = template.index("rig not found on this host")
    assert fault < fallback, "fault handling must come before the absent-rig fallback"


def test_non_interactive_session_refuses_the_fallback():
    """The fallback is only safe because a human reads the warning. In CI nobody does,
    and an unleased host run can collide with another."""
    template = runner_template()
    assert "CI:-" in template and "GITHUB_ACTIONS:-" in template
    assert "Refusing in a non-interactive session" in template
    assert "non-interactive" in ROUTE


# --- "green and empty" is a failure, not a pass -----------------------------------

def test_executed_is_derived_and_zero_is_a_failure():
    """Every test skipped, nothing run, exit 0 reads as success. `executed` is the number
    that says whether anything happened — and it is DERIVED from the two validated
    counts, never read from the rig, so a malformed field cannot reach the comparison.
    (Round 3 tightened this: the earlier `.executed // …` fallback trusted the rig's own
    value when it was present, which is the surface this removes.)"""
    template = runner_template()
    assert "green and empty is not a pass" in template
    assert "0 tests executed" in template
    assert "SKIPPED ))" in template, "executed must be computed from total and skipped"
    assert "skipped=" in template, "skipped must be printed in plain text on every run"


def test_the_block_tells_the_reader_to_treat_zero_executed_as_failure():
    assert "executed == 0" in XCODE_BLOCK
    assert "Green and empty" in XCODE_BLOCK


# --- layering: who writes the pin, who only reads it ------------------------------

def test_only_the_generators_write_the_pin():
    for name, text in (("adapt", ADAPT), ("setup-routing", SETUP)):
        assert ".gstack/e2e-executor" in text, name
        assert "!\\.gstack/e2e-executor" in text or "!.gstack/e2e-executor" in text, \
            f"{name} must keep the pin committable when .gstack/ is ignored"
    assert "never its writer" in ROUTE, "e2e-route must stay a pure reader"


def test_the_axis_is_macos_only():
    """iOS routes to its own scaffold and has no rig; asking there would be a question
    with no useful answer."""
    assert "macos" in ADAPT[ADAPT.index("{{E2E_EXECUTOR}}"):][:400]
    assert "macOS-only" in ROUTE or "committed macOS only" in ROUTE


def test_block_marker_and_placeholder_are_wired():
    assert "<!-- gstack-xcode-tools-v7 -->" in XCODE_BLOCK
    assert "{{E2E_EXECUTOR}}" in XCODE_BLOCK
    assert "{{E2E_EXECUTOR}}" in PLACEHOLDERS, "every placeholder needs a resolution rule"
    ladder = ADAPT[ADAPT.index("Native Apple development tools section."):][:2500]
    assert "matches `v7`" in ladder, "adapt's version ladder must skip on v7"
    assert "`v1`–`v6`" in ladder, "and must replace v6 and older"


def test_route_decision_block_carries_the_executor_field():
    assert "executor=<host|vm|vm→host-fallback>" in ROUTE


# --- the shipped hook actually behaves ---------------------------------------------

@pytest.mark.parametrize("pin,why", [
    (None, "no pin at all — the common case, must be silent"),
    ("host", "explicit host — nothing to report"),
    ("garbage", "invalid pin is the runner's error to raise, not the hook's"),
])
def test_vm_hygiene_is_silent_unless_the_project_opted_in(pin, why):
    """This hook ships to every plugin user. One that talks in projects that never
    opted in is a hook people disable, taking the useful case with it."""
    with tempfile.TemporaryDirectory() as d:
        subprocess.run(["git", "init", "-q"], cwd=d, check=True)
        if pin is not None:
            (Path(d) / ".gstack").mkdir()
            (Path(d) / ".gstack" / "e2e-executor").write_text(pin + "\n")
        p = subprocess.run(["bash", str(HYGIENE)], cwd=d, capture_output=True, text=True)
        assert p.returncode == 0, why
        assert p.stdout == "", f"{why}: printed {p.stdout!r}"


def test_vm_hygiene_never_stops_a_vm():
    """The rig's rule: no automation stops a guest, because a VM you did not start may
    be someone else's run. Report only."""
    text = HYGIENE.read_text()
    assert "Reports, never acts" in text
    assert not re.search(r"^\s*(vm-stop|kill|pkill)\s", text, re.M), \
        "the hook must not stop anything — only name what it found"


# --- Codex round 1 on 2.53.0: four ways this could still report a false green ---

def test_a_nonzero_rig_status_survives_a_clean_looking_summary():
    """The counts can parse and look green while the rig still failed — an xcodebuild
    infrastructure error, a half-completed transfer. Reading only `failed` discards the
    rig's own verdict and turns that into a pass."""
    template = runner_template()
    assert "VM_STATUS" in template
    assert 'exit "$VM_STATUS"' in template, "the rig's exit code must be able to fail the run"
    assert "despite a clean-looking summary" in flat(template)


def test_the_pin_is_trimmed_at_the_edges_not_squeezed():
    """`tr -d '[:space:]'` turns `v m` into a valid `vm` — normalising junk into a legal
    value is the opposite of validating it. Trim the generators' trailing newline only."""
    # Assert on the CODE, not the file: the runner's comment names `tr -d '[:space:]'`
    # to explain why it is wrong, and a bare substring check would flag that explanation
    # as the defect it warns against.
    for surface, text in (("runner", runner_template()), ("hook", HYGIENE.read_text())):
        code = [l for l in text.splitlines() if not l.lstrip().startswith("#")]
        assert not any("tr -d '[:space:]'" in l for l in code), \
            f"{surface} must not squeeze interior whitespace"
    # The runner reads the WHOLE file via $( ) — strictest, and simplest. The hook only
    # needs to recognise `vm`, so a first-line read suffices there; neither squeezes.
    assert "EXECUTOR=$(cat .gstack/e2e-executor)" in runner_template()
    assert "head -1" in HYGIENE.read_text()


def test_direct_vm_dispatch_requires_an_existing_suite():
    """The pin is written at onboarding, before any suite necessarily exists. A `vm` pin
    alone must not route a project with no tests straight at the rig."""
    assert "*UITests" in ROUTE, "the route must actually check for a UI-test target"
    assert "before any suite necessarily exists" in flat(ROUTE)


def test_a_host_pinned_suite_without_a_runner_has_a_route():
    """Legacy or hand-made suite + `host` pin + no runner script matched no entry point
    at all before this: 1 needs the script, 2 is VM-only, 4 excludes existing targets."""
    assert "-only-testing:<Target>" in ROUTE
    assert "without this the project matches no entry point at all" in flat(ROUTE)


def test_non_interactive_detection_is_honest_about_its_limits():
    """`--print` and subagent dispatch are not visible from a Bash call, and a TTY check
    answers the wrong question because an agent's Bash tool always pipes stdout. The
    caller sets the variable; the script does not guess."""
    assert "E2E_NONINTERACTIVE" in ROUTE and "E2E_NONINTERACTIVE" in runner_template()
    assert "pipes stdout even when a human is watching" in flat(ROUTE)
    assert "Guessing \"probably automated\" from a pipe would refuse the ordinary case" in flat(ROUTE)


def test_the_hook_reads_the_marker_from_the_repo_root():
    """A session started in a subdirectory would otherwise miss the marker entirely and
    go silent for a project that did opt in."""
    text = HYGIENE.read_text()
    assert "git rev-parse --show-toplevel" in text
    assert '"$ROOT/.gstack/e2e-executor"' in text


def test_the_hook_does_not_guess_the_rigs_lease_vocabulary():
    """The rig prints its own words (today Norwegian). An English word list here matches
    nothing and the hook stays quiet about the one thing it was added to report."""
    text = HYGIENE.read_text()
    assert "grep -i 'busy" not in text, "do not pattern-match the rig's status words"
    assert "vm-lease status" in text and "let the reader judge" in flat(text)


# --- Codex round 2 on 2.53.0 ---

@pytest.mark.parametrize("raw,valid", [
    ("vm\n", True), ("host\n", True), ("vm", True), ("host", True),
    ("vm ", False), ("v m", False), ("VM\n", False), ("", False),
    ("vm\ncomment\n", False), (" vm\n", False),
])
def test_pin_validation_accepts_only_the_generators_exact_output(raw, valid):
    """Live-tests the shell the runner ships, not its prose. `$( )` strips exactly the
    trailing newline the generators write, so everything else — a trailing space, an
    interior gap, a second line — reaches the case and is refused. `head -1 | sed` and
    `tr -d '[:space:]'` both normalise those into a legal value instead."""
    with tempfile.TemporaryDirectory() as d:
        (Path(d) / ".gstack").mkdir()
        (Path(d) / ".gstack" / "e2e-executor").write_text(raw)
        script = '''
EXECUTOR=$(cat .gstack/e2e-executor)
case "$EXECUTOR" in
  host|vm) echo "OK:$EXECUTOR" ;;
  *) echo "BLOCKED"; exit 2 ;;
esac
'''
        p = subprocess.run(["bash", "-c", script], cwd=d, capture_output=True, text=True)
        accepted = p.returncode == 0
        assert accepted is valid, f"{raw!r} -> {p.stdout.strip()!r}"


@pytest.mark.parametrize("payload,usable,why", [
    ('{"total":16,"passed":7,"failed":0,"skipped":9}', True,  "a real result"),
    ('{"total":1,"executed":1,"error":"copy failed"}', False, "rig reported its own failure"),
    ('{"total":1,"failed":"none"}',                    False, "non-numeric failed"),
    ('{"total":1,"skipped":null}',                     False, "null skipped"),
    ('{"total":null}',                                 False, "null total"),
    ('{"error":"VM boot timed out"}',                  False, "error-only shape"),
])
def test_vm_result_schema_is_validated_before_it_is_trusted(payload, usable, why):
    """A parseable object is not automatically a usable result: with a missing `failed`
    defaulting to 0, a rig that reported its own failure would print as a green summary."""
    guard = ('type == "object" and (.error // null | . == null) '
             'and (.total | type == "number") '
             'and ((has("failed") | not) or (.failed | type == "number")) '
             'and ((has("skipped") | not) or (.skipped | type == "number"))')
    with tempfile.NamedTemporaryFile("w", suffix=".json", delete=False) as f:
        f.write(payload); path = f.name
    try:
        rc = subprocess.run(["jq", "-e", guard, path], capture_output=True).returncode
        assert (rc == 0) is usable, why
        assert flat(guard) in flat(runner_template()), \
            "the shipped runner must use this exact guard (whitespace aside)"
    finally:
        os.unlink(path)


def test_the_oracle_row_lists_every_entry_point():
    """The table is authoritative. A row that skips entry point 3 sends a legacy
    host-pinned suite to the scaffold, which refuses, which used to mean MCP-live —
    and the regression never runs."""
    row = [l for l in ROUTE.splitlines() if l.startswith("| Committed regression | macOS")]
    assert len(row) == 1
    assert "run-uitests.sh" in row[0] and "vm-e2e" in row[0] and "-only-testing:" in row[0] \
        and "macos-e2e-scaffold" in row[0]


def test_existing_target_is_not_a_fallback_trigger_for_committed_intent():
    assert "is NOT a fallback trigger for" in flat(ROUTE)
    fallback = ROUTE[ROUTE.index("## Fallback"):]
    numbered = [l for l in fallback.splitlines() if l.startswith("3. a UI-test target")]
    assert not numbered, "refuse-condition 3 must not sit in the numbered fallback list"


def test_a_held_lease_is_reported_even_with_no_process_left():
    """The stale-lease case: nothing running, but the next dispatch is still blocked.
    Gating the lease check on process findings made exactly that case silent."""
    text = HYGIENE.read_text()
    assert "grep -vE 'ledig|free|idle|available'" in text, \
        "match the absence of the free marker, not a guessed word for held"
    held_line = text.index("held=$(vm-lease status")
    gate = text.find("${#findings[@]} -gt 0")
    assert gate == -1 or gate > held_line, "the lease check must not depend on other findings"


# --- Codex round 3 on 2.53.0 ---

def test_the_shared_runner_path_is_gated_on_a_macos_target():
    """`scripts/run-uitests.sh` is a SHARED path: /ios-e2e-scaffold writes one there too.
    Ungated, a committed macOS request in a project scaffolded for iOS first would run
    the iOS suite and never reach the macOS scaffold."""
    assert "shared path" in flat(ROUTE)
    assert "! -name '*iOSUITests'" in ROUTE
    gate = ROUTE.index("Entry points 1–3 all require")
    entry1 = ROUTE.index("1. `./scripts/run-uitests.sh` exists")
    assert gate < entry1, "the target check must be stated before entry point 1, not after"


def test_executed_is_derived_never_taken_from_the_rig():
    """A present-but-non-numeric `.executed` passes a guard that checks total/failed/
    skipped, then `[ -eq 0 ]` fails with status 2 — and without `set -e` the script
    continues and exits 0. Deriving removes the field from the trust surface."""
    template = runner_template()
    assert "EXECUTED=$(( $(jq -r '.total' \"$VM_JSON\") - SKIPPED ))" in template
    assert ".executed //" not in template, \
        "the rig's own executed field must not be read back as a fallback"
    assert "never trust the\n    # rig's own field" in template


def test_the_placeholder_resolver_validates_before_it_normalises():
    """A generator following the documented command must not be the one path that
    launders `v m` into a valid pin."""
    assert "tr -d '[:space:]'" not in PLACEHOLDERS.split("Do NOT")[0], \
        "the resolver command itself must not squeeze whitespace"
    assert 'case "$(cat .gstack/e2e-executor)" in' in PLACEHOLDERS
    assert "BLOCKED — invalid .gstack/e2e-executor" in PLACEHOLDERS


def test_the_runner_resolves_the_pin_from_the_project_root():
    """Invoked from a subdirectory, a relative read finds no pin and proceeds as host —
    so an INVALID pin degrades to a silent host run, the one outcome the marker exists
    to prevent. Drives the real template from both directories."""
    tmpl = runner_template().replace("<APP>", "X").replace("<TARGET_DIR>", "XUITests")
    with tempfile.TemporaryDirectory() as d:
        root = Path(d)
        (root / ".gstack").mkdir(); (root / "scripts").mkdir(); (root / "sub").mkdir()
        (root / ".gstack" / "e2e-executor").write_text("VM\n")   # invalid on purpose
        runner = root / "scripts" / "run-uitests.sh"
        runner.write_text("#!/usr/bin/env bash\n" + tmpl); runner.chmod(0o755)
        for cwd in (root, root / "sub"):
            p = subprocess.run(["bash", str(runner)], cwd=cwd,
                               capture_output=True, text=True, timeout=30)
            assert p.returncode == 2, f"from {cwd.name}: exit {p.returncode}"
            assert "BLOCKED" in p.stderr, f"from {cwd.name}: an invalid pin was not refused"
