"""Guard the `.gstack/e2e-executor` axis — the one pin that can lie quietly.

Every other failure in this feature announces itself: a VM that will not boot, a rig
that is not installed, a test that fails. The dangerous one is a run that looks
completely normal while executing somewhere the user did not choose — a `VM` typo
degrading to host, or every test skipped and exit 0.

So these tests hold three properties: the pin is validated rather than coerced, an
absent rig and a failing rig get opposite treatment, and `executed` is always visible.
They assert on SKILL.md prose the way test_spec_drift_skill.py does, because these
contracts live in text an agent reads, plus real behaviour for the shell that ships —
the runner template at skills/e2e-scaffold/templates/run-uitests.sh.
"""
from __future__ import annotations

import os
import re
import subprocess
import sys
import tempfile
from pathlib import Path

import pytest

REPO = Path(__file__).resolve().parents[2]
ROUTE = (REPO / "skills" / "e2e-route" / "SKILL.md").read_text()
RUNNER = (REPO / "skills" / "e2e-scaffold" / "templates" / "run-uitests.sh").read_text()
XCODE_BLOCK = (REPO / "skills" / "setup-routing" / "blocks" / "xcode-tools.md").read_text()
PLACEHOLDERS = (REPO / "skills" / "setup-routing" / "blocks" / "PLACEHOLDERS.md").read_text()
ADAPT = (REPO / "skills" / "adapt" / "SKILL.md").read_text()
SETUP = (REPO / "skills" / "setup-routing" / "SKILL.md").read_text()
HYGIENE = REPO / "scripts" / "vm-hygiene.sh"


def runner_template() -> str:
    """The generated scripts/run-uitests.sh, as the scaffold skill ships it.

    The template is its own file (not a fenced block in SKILL.md), so it is read whole.
    The header is the unversioned `# Auto-generated by /e2e-scaffold`; the SPM-only stub
    in SKILL.md shares that prefix but lives in the prose, not here.
    """
    assert RUNNER.startswith("#!/usr/bin/env bash\n# Auto-generated by /e2e-scaffold\n"), \
        "the runner header must be the literal, unversioned banner"
    return RUNNER


def flat(text: str) -> str:
    """Whitespace-collapsed, so an assertion does not depend on where prose wrapped."""
    return " ".join(text.split())


# --- the pin is validated, never coerced ------------------------------------------

# Explicit ids: the parameters here are whole SKILL.md files, and pytest would otherwise
# derive multi-thousand-character node ids from them, put those in PYTEST_CURRENT_TEST,
# and hand every spawned subprocess an oversized environment — E2BIG on Linux, fine on
# macOS. That is the 2.52.1 bug; test_node_id_budget.py caught this very test.
@pytest.mark.parametrize("surface,text", [
    pytest.param("runner template", runner_template(), id="runner-template"),
    pytest.param("e2e-route", ROUTE, id="e2e-route"),
    pytest.param("xcode-tools block", XCODE_BLOCK, id="xcode-tools-block"),
    pytest.param("PLACEHOLDERS", PLACEHOLDERS, id="placeholders"),
])
def test_an_invalid_pin_is_refused_not_treated_as_host(surface, text):
    """`VM`, a trailing space or a stray comment must not degrade to host. Coercing an
    unrecognised value is indistinguishable from success at the point it matters."""
    assert "BLOCKED — invalid .gstack/e2e-executor" in flat(text), surface


def test_absence_of_the_file_means_host_everywhere():
    """The default is defined, not incidental — a project that never opts in must read
    correctly rather than hit an error path."""
    for surface, text in (("route", ROUTE), ("block", XCODE_BLOCK), ("placeholders", PLACEHOLDERS)):
        assert re.search(r"absen\w+ (of the file )?means?\s+`?host`?|file's absence means", text), surface


# --- absent rig and failing rig are opposites -------------------------------------

def test_missing_rig_falls_back_loudly():
    template = runner_template()
    assert "rig not found on this host — running on host without lease" in template
    assert "rig not found on this host — running on host without lease" in ROUTE, \
        "the route's decision block must carry the same wording the runner prints"


def test_a_failing_rig_does_not_fall_back():
    """The distinction the whole design turns on: a rig FAULT is the thing to surface.
    Running on the host instead converts a real defect into a silently slower pass."""
    template = runner_template()
    assert "E2E RIG FAILED" in template
    assert "Not falling back to the host" in template
    fault = template.index("E2E RIG FAILED")
    fallback = template.index("rig not found on this host")
    assert fault < fallback, "fault handling must come before the absent-rig fallback"


def test_non_interactive_session_refuses_the_fallback():
    """The fallback is only safe because a human reads the warning. In CI nobody does,
    and an unleased host run can collide with another."""
    template = runner_template()
    assert "CI:-" in template and "GITHUB_ACTIONS:-" in template
    assert "Refusing in a non-interactive session" in template
    assert "non-interactive" in ROUTE


# --- "green and empty" is a failure, not a pass -----------------------------------

def test_executed_is_derived_and_zero_is_a_failure():
    """Every test skipped, nothing run, exit 0 reads as success. `executed` is the number
    that says whether anything happened — and it is DERIVED from the two validated
    counts, never read from the rig, so a malformed field cannot reach the comparison.
    (Round 3 tightened this: the earlier `.executed // …` fallback trusted the rig's own
    value when it was present, which is the surface this removes.)"""
    template = runner_template()
    assert "green and empty is not a pass" in template
    assert "0 tests executed" in template
    assert "SKIPPED ))" in template, "executed must be computed from total and skipped"
    assert "skipped=" in template, "skipped must be printed in plain text on every run"


def test_the_block_tells_the_reader_to_treat_zero_executed_as_failure():
    assert "executed == 0" in XCODE_BLOCK
    assert "Green and empty" in XCODE_BLOCK


# --- layering: who writes the pin, who only reads it ------------------------------

def test_only_the_generators_write_the_pin():
    for name, text in (("adapt", ADAPT), ("setup-routing", SETUP)):
        assert ".gstack/e2e-executor" in text, name
        assert "!\\.gstack/e2e-executor" in text or "!.gstack/e2e-executor" in text, \
            f"{name} must keep the pin committable when .gstack/ is ignored"
    assert "never its writer" in ROUTE, "e2e-route must stay a pure reader"


def test_the_axis_is_macos_only():
    """iOS routes to its own scaffold and has no rig; asking there would be a question
    with no useful answer."""
    assert "macos" in ADAPT[ADAPT.index("{{E2E_EXECUTOR}}"):][:400]
    assert "macOS-only" in ROUTE or "committed macOS only" in ROUTE


def test_block_marker_and_placeholder_are_wired():
    assert "<!-- gstack-xcode-tools-v7 -->" in XCODE_BLOCK
    assert "{{E2E_EXECUTOR}}" in XCODE_BLOCK
    assert "{{E2E_EXECUTOR}}" in PLACEHOLDERS, "every placeholder needs a resolution rule"
    ladder = ADAPT[ADAPT.index("Native Apple development tools section."):][:2500]
    assert "matches `v7`" in ladder, "adapt's version ladder must skip on v7"
    assert "`v1`–`v6`" in ladder, "and must replace v6 and older"


def test_route_decision_block_carries_the_executor_field():
    assert "executor=<host|vm|vm→host-fallback>" in ROUTE


# --- the shipped hook actually behaves ---------------------------------------------

@pytest.mark.parametrize("pin,why", [
    (None, "no pin at all — the common case, must be silent"),
    ("host", "explicit host — nothing to report"),
    ("garbage", "invalid pin is the runner's error to raise, not the hook's"),
])
def test_vm_hygiene_is_silent_unless_the_project_opted_in(pin, why):
    """This hook ships to every plugin user. One that talks in projects that never
    opted in is a hook people disable, taking the useful case with it."""
    with tempfile.TemporaryDirectory() as d:
        subprocess.run(["git", "init", "-q"], cwd=d, check=True)
        if pin is not None:
            (Path(d) / ".gstack").mkdir()
            (Path(d) / ".gstack" / "e2e-executor").write_text(pin + "\n")
        p = subprocess.run(["bash", str(HYGIENE)], cwd=d, capture_output=True, text=True)
        assert p.returncode == 0, why
        assert p.stdout == "", f"{why}: printed {p.stdout!r}"


def test_vm_hygiene_never_stops_a_vm():
    """The rig's rule: no automation stops a guest, because a VM you did not start may
    be someone else's run. Report only."""
    text = HYGIENE.read_text()
    assert "Reports, never acts" in text
    assert not re.search(r"^\s*(vm-stop|kill|pkill)\s", text, re.M), \
        "the hook must not stop anything — only name what it found"


# --- Codex round 1 on 2.53.0: four ways this could still report a false green ---

def test_a_nonzero_rig_status_survives_a_clean_looking_summary():
    """The counts can parse and look green while the rig still failed — an xcodebuild
    infrastructure error, a half-completed transfer. Reading only `failed` discards the
    rig's own verdict and turns that into a pass."""
    template = runner_template()
    assert "VM_STATUS" in template
    assert 'exit "$VM_STATUS"' in template, "the rig's exit code must be able to fail the run"
    assert "despite a clean-looking summary" in flat(template)


def test_the_pin_is_trimmed_at_the_edges_not_squeezed():
    """`tr -d '[:space:]'` turns `v m` into a valid `vm` — normalising junk into a legal
    value is the opposite of validating it. Trim the generators' trailing newline only."""
    # Assert on the CODE, not the file: the runner's comment names `tr -d '[:space:]'`
    # to explain why it is wrong, and a bare substring check would flag that explanation
    # as the defect it warns against.
    for surface, text in (("runner", runner_template()), ("hook", HYGIENE.read_text())):
        code = [l for l in text.splitlines() if not l.lstrip().startswith("#")]
        assert not any("tr -d '[:space:]'" in l for l in code), \
            f"{surface} must not squeeze interior whitespace"
    # The runner reads the WHOLE file via $( ) — strictest, and simplest. The hook only
    # needs to recognise `vm`, so a first-line read suffices there; neither squeezes.
    assert "EXECUTOR=$(cat .gstack/e2e-executor)" in runner_template()
    assert "head -1" in HYGIENE.read_text()


def test_direct_vm_dispatch_requires_an_existing_suite():
    """The pin is written at onboarding, before any suite necessarily exists. A `vm` pin
    alone must not route a project with no tests straight at the rig."""
    assert "*UITests" in ROUTE, "the route must actually check for a UI-test target"
    assert re.search(r"before any suite (necessarily )?exists", flat(ROUTE))


def test_a_host_pinned_suite_without_a_runner_has_a_route():
    """Legacy or hand-made suite + `host` pin + no runner script matched no entry point
    at all before this: 1 needs the script, 2 is VM-only, 4 excludes existing targets."""
    assert "-only-testing:<Target>" in ROUTE
    assert re.search(r"^3\. .*target exists.*host", ROUTE, re.M), \
        "entry point 3 (existing target, no runner, host run) must be a numbered entry"


def test_non_interactive_detection_is_honest_about_its_limits():
    """`--print` and subagent dispatch are not visible from a Bash call, and a TTY check
    answers the wrong question because an agent's Bash tool always pipes stdout. The
    caller sets the variable; the script does not guess."""
    assert "E2E_NONINTERACTIVE" in ROUTE and "E2E_NONINTERACTIVE" in runner_template()
    assert "cannot detect the session kind itself" in flat(ROUTE), \
        "the route must say the runner cannot detect --print / subagent dispatch"
    assert "--print" in ROUTE and "subagent" in ROUTE


def test_the_hook_reads_the_marker_from_the_repo_root():
    """A session started in a subdirectory would otherwise miss the marker entirely and
    go silent for a project that did opt in."""
    text = HYGIENE.read_text()
    assert "git rev-parse --show-toplevel" in text
    assert '"$ROOT/.gstack/e2e-executor"' in text


def test_the_hook_does_not_guess_the_rigs_lease_vocabulary():
    """The rig prints its own words (today Norwegian). An English word list here matches
    nothing and the hook stays quiet about the one thing it was added to report."""
    text = HYGIENE.read_text()
    assert "grep -i 'busy" not in text, "do not pattern-match the rig's status words"
    assert "vm-lease status" in text and "let the reader judge" in flat(text)


# --- Codex round 2 on 2.53.0 ---

@pytest.mark.parametrize("raw,valid", [
    ("vm\n", True), ("host\n", True), ("vm", True), ("host", True),
    ("vm ", False), ("v m", False), ("VM\n", False), ("", False),
    ("vm\ncomment\n", False), (" vm\n", False),
])
def test_pin_validation_accepts_only_the_generators_exact_output(raw, valid):
    """Live-tests the shell the runner ships, not its prose. `$( )` strips exactly the
    trailing newline the generators write, so everything else — a trailing space, an
    interior gap, a second line — reaches the case and is refused. `head -1 | sed` and
    `tr -d '[:space:]'` both normalise those into a legal value instead."""
    with tempfile.TemporaryDirectory() as d:
        (Path(d) / ".gstack").mkdir()
        (Path(d) / ".gstack" / "e2e-executor").write_text(raw)
        script = '''
EXECUTOR=$(cat .gstack/e2e-executor)
case "$EXECUTOR" in
  host|vm) echo "OK:$EXECUTOR" ;;
  *) echo "BLOCKED"; exit 2 ;;
esac
'''
        p = subprocess.run(["bash", "-c", script], cwd=d, capture_output=True, text=True)
        accepted = p.returncode == 0
        assert accepted is valid, f"{raw!r} -> {p.stdout.strip()!r}"


@pytest.mark.parametrize("payload,usable,why", [
    ('{"total":16,"passed":7,"failed":0,"skipped":9}', True,  "a real result"),
    ('{"total":1,"executed":1,"error":"copy failed"}', False, "rig reported its own failure"),
    ('{"total":1,"failed":"none"}',                    False, "non-numeric failed"),
    ('{"total":1,"skipped":null}',                     False, "null skipped"),
    ('{"total":null}',                                 False, "null total"),
    ('{"error":"VM boot timed out"}',                  False, "error-only shape"),
])
def test_vm_result_schema_is_validated_before_it_is_trusted(payload, usable, why):
    """A parseable object is not automatically a usable result: with a missing `failed`
    defaulting to 0, a rig that reported its own failure would print as a green summary."""
    guard = ('type == "object" and (.error // null | . == null) '
             'and (.total | type == "number") '
             'and ((has("failed") | not) or (.failed | type == "number")) '
             'and ((has("skipped") | not) or (.skipped | type == "number"))')
    with tempfile.NamedTemporaryFile("w", suffix=".json", delete=False) as f:
        f.write(payload); path = f.name
    try:
        rc = subprocess.run(["jq", "-e", guard, path], capture_output=True).returncode
        assert (rc == 0) is usable, why
        assert flat(guard) in flat(runner_template()), \
            "the shipped runner must use this exact guard (whitespace aside)"
    finally:
        os.unlink(path)


def test_the_oracle_row_lists_every_entry_point():
    """The table is authoritative. A row that skips entry point 3 sends a legacy
    host-pinned suite to the scaffold, which refuses, which used to mean MCP-live —
    and the regression never runs."""
    row = [l for l in ROUTE.splitlines() if l.startswith("| Committed regression | macOS")]
    assert len(row) == 1
    assert "Entry points 1–4" in row[0] and ".gstack/e2e-executor" in row[0]
    entries = ROUTE[ROUTE.index("**Committed macOS entry points.**"):ROUTE.index("## Fallback")]
    numbered = [l for l in entries.splitlines() if re.match(r"^[1-4]\. ", l)]
    assert len(numbered) == 4, "all four entry points must be numbered, in order"
    assert "run-uitests.sh" in numbered[0] and "vm-e2e" in numbered[1] \
        and "-only-testing:" in entries and "e2e-scaffold" in numbered[3]


def test_existing_target_is_not_a_fallback_trigger_for_committed_intent():
    assert "already has a suite routes to 1–3, never to exploratory" in flat(ROUTE)
    fallback = ROUTE[ROUTE.index("## Fallback"):ROUTE.index("**Waiting.**")]
    assert "already exists" not in fallback, \
        "refuse-condition 3 (target already exists) must not be listed as a fallback trigger"


def test_a_held_lease_is_reported_even_with_no_process_left():
    """The stale-lease case: nothing running, but the next dispatch is still blocked.
    Gating the lease check on process findings made exactly that case silent."""
    text = HYGIENE.read_text()
    assert "grep -vE 'ledig|free|idle|available'" in text, \
        "match the absence of the free marker, not a guessed word for held"
    held_line = text.index("held=$(vm-lease status")
    gate = text.find("${#findings[@]} -gt 0")
    assert gate == -1 or gate > held_line, "the lease check must not depend on other findings"


# --- Codex round 3 on 2.53.0 ---

def test_the_shared_runner_path_is_gated_on_a_macos_target():
    """`scripts/run-uitests.sh` is a SHARED path: /e2e-scaffold writes the same file for
    an iOS run. Ungated, a committed macOS request in a project scaffolded for iOS first
    would run the iOS suite and never reach the macOS scaffold."""
    assert "If the only suite is the iOS one, this falls through to 4" in flat(ROUTE)
    assert "! -name '*iOSUITests'" in ROUTE
    gate = ROUTE.index("Entries 1–3 require a macOS UI-test target")
    entry1 = ROUTE.index("1. `./scripts/run-uitests.sh` exists")
    assert gate < entry1, "the target check must be stated before entry point 1, not after"


def test_executed_is_derived_never_taken_from_the_rig():
    """A present-but-non-numeric `.executed` passes a guard that checks total/failed/
    skipped, then `[ -eq 0 ]` fails with status 2 — and without `set -e` the script
    continues and exits 0. Deriving removes the field from the trust surface."""
    template = runner_template()
    assert "EXECUTED=$(( $(jq -r '.total' \"$VM_JSON\") - SKIPPED ))" in template
    assert ".executed //" not in template, \
        "the rig's own executed field must not be read back as a fallback"
    assert "never trust the rig's own field" in flat(template)


def test_the_placeholder_resolver_validates_before_it_normalises():
    """A generator following the documented command must not be the one path that
    launders `v m` into a valid pin."""
    assert "tr -d '[:space:]'" not in PLACEHOLDERS.split("Do NOT")[0], \
        "the resolver command itself must not squeeze whitespace"
    assert 'case "$(cat .gstack/e2e-executor)" in' in PLACEHOLDERS
    assert "BLOCKED — invalid .gstack/e2e-executor" in PLACEHOLDERS


def test_the_runner_resolves_the_pin_from_the_project_root():
    """Invoked from a subdirectory, a relative read finds no pin and proceeds as host —
    so an INVALID pin degrades to a silent host run, the one outcome the marker exists
    to prevent. Drives the real template from both directories."""
    tmpl = (runner_template().replace("<SCHEME>", "X").replace("<PLATFORM>", "macos")
            .replace("<TEST_TARGET>", "XUITests"))
    with tempfile.TemporaryDirectory() as d:
        root = Path(d)
        (root / ".gstack").mkdir(); (root / "scripts").mkdir(); (root / "sub").mkdir()
        (root / ".gstack" / "e2e-executor").write_text("VM\n")   # invalid on purpose
        runner = root / "scripts" / "run-uitests.sh"
        runner.write_text(tmpl); runner.chmod(0o755)
        for cwd in (root, root / "sub"):
            p = subprocess.run(["bash", str(runner)], cwd=cwd,
                               capture_output=True, text=True, timeout=30)
            assert p.returncode == 2, f"from {cwd.name}: exit {p.returncode}"
            assert "BLOCKED" in p.stderr, f"from {cwd.name}: an invalid pin was not refused"


# --- 2.53.2: the axis reached the template but not already-generated runners ---

def test_route_checks_that_an_existing_runner_honours_the_axis():
    """The scaffold template reads the pin; runners already written into projects before
    the pin existed do not. Through entry point 1 such a runner runs `executor=vm` on the
    host silently — the very failure the pin exists to catch. Reported by the rig session,
    which hit it in swiftconfig."""
    assert r"grep -qE '\.gstack/e2e-executor' scripts/run-uitests.sh" in ROUTE
    assert "LEGACY" in ROUTE
    assert "heuristic over text, not proof" in flat(ROUTE), \
        "say what the check cannot prove — a comment naming the path would pass it"


@pytest.mark.parametrize("body,honours,why", [
    ("#!/usr/bin/env bash\n# Auto-generated by /macos-e2e-scaffold v1.10.0\n"
     "xcodebuild test -scheme X -quiet\n", False, "the real pre-2.53.0 shape"),
    ("#!/usr/bin/env bash\nif [ -f .gstack/e2e-executor ]; then :; fi\n", True,
     "any runner that reads the pin"),
])
def test_the_legacy_detection_separates_old_from_new(body, honours, why):
    with tempfile.TemporaryDirectory() as d:
        p = Path(d) / "run-uitests.sh"; p.write_text(body)
        rc = subprocess.run(["grep", "-qE", r"\.gstack/e2e-executor", str(p)]).returncode
        assert (rc == 0) is honours, why


def test_rig_exit_2_settles_the_question_before_json_is_read():
    """Exit 2 is declared, not inferred. The JSON checks stay as defence in depth and as
    the only signal from a rig older than the three-valued contract — but where the rig
    states it, the state is not something to deduce from the shape of its output."""
    template = runner_template()
    assert '[ "$VM_STATUS" -eq 2 ]' in template
    exit2 = template.index('[ "$VM_STATUS" -eq 2 ]')
    schema = template.index("type == \"object\"")
    assert exit2 < schema, "the declared signal must be checked before the inferred one"
    assert "defence in depth" in flat(template)


# --- 3.0.0: the template became one file for both platforms — drive it end to end ---

def _summary(total, passed, failed, skipped):
    """What `xcrun xcresulttool get test-results summary --format json` prints."""
    import json
    failures = [{"testIdentifier": f"XUITests/t{i}",
                 "sourceCodeContext": {"location": {"filePath": "a.swift", "lineNumber": 1}},
                 "failureText": "boom"} for i in range(failed)]
    return json.dumps({"totalTestCount": total, "passedTests": passed, "failedTests": failed,
                       "skippedTests": skipped, "testFailures": failures or None})


def _stub_bins(d: Path, with_rig: bool) -> Path:
    """xcodebuild / xcrun / automationmodetool / vm-e2e stand-ins, all driven by STUB_* env."""
    b = d / "bin"; b.mkdir()
    stubs = {
        "xcodebuild": 'printf "%s\\n" "$*" > "$STUB_LOG/xcodebuild.args"\nexit "${STUB_XCB_STATUS:-0}"\n',
        "xcrun": ('case "$1 $2" in\n'
                  '  "simctl list") printf "%s\\n" "$STUB_SIMS" ;;\n'
                  '  "xcresulttool get") if [ "$3" = test-results ]; then printf "%s" "$STUB_SUMMARY";'
                  ' else echo "plaintext result"; fi ;;\n'
                  'esac\n'),
        "automationmodetool": 'echo "automationmodetool: DOES NOT REQUIRE"\n',
    }
    if with_rig:
        stubs["vm-e2e"] = ('while [ $# -gt 0 ]; do case "$1" in --json) J="$2"; shift ;; esac; shift; done\n'
                           'printf "%s" "$STUB_VM_JSON" > "$J"\nexit "${STUB_VM_STATUS:-0}"\n')
    for name, body in stubs.items():
        p = b / name; p.write_text("#!/usr/bin/env bash\n" + body); p.chmod(0o755)
    return b


SIM = "    iPhone 17 (ABCDEF01-1234-1234-1234-1234567890AB) (Shutdown)"
GREEN = _summary(2, 2, 0, 0)


@pytest.mark.parametrize("platform,pin,rig,env,rc,stderr_has,stdout_has,xcb_ran,dest", [
    pytest.param("ios", None, False, {"STUB_SIMS": ""}, 2,
                 "No iPhone simulator available", "", False, None, id="ios-no-simulator-exit-2"),
    pytest.param("ios", None, False, {"STUB_SIMS": SIM, "STUB_SUMMARY": GREEN}, 0,
                 "(using iPhone simulator ABCDEF01-1234-1234-1234-1234567890AB)", '"executor": "host"',
                 True, "platform=iOS Simulator,id=ABCDEF01-1234-1234-1234-1234567890AB",
                 id="ios-targets-the-simulator-by-udid"),
    pytest.param("ios", "vm\n", False, {"STUB_SIMS": SIM, "STUB_SUMMARY": GREEN}, 0,
                 "executor=vm pin applies to macOS only", '"executor": "host"', True, None,
                 id="ios-ignores-the-vm-pin-loudly"),
    pytest.param("macos", None, False, {"STUB_SUMMARY": _summary(2, 1, 1, 0), "STUB_XCB_STATUS": "65"}, 65,
                 "executor=host", '"failed": 1', True, "platform=macOS",
                 id="macos-passes-xcodebuild-status-through-not-1"),
    pytest.param("macos", None, False, {"STUB_SUMMARY": _summary(3, 0, 0, 3)}, 1,
                 "0 tests executed", '"executed": 0', True, None,
                 id="macos-green-and-empty-is-exit-1"),
    pytest.param("macos", None, False, {"STUB_SUMMARY": ""}, 2,
                 "could not verify that any test executed", "plaintext result", True, None,
                 id="macos-old-xcode-plaintext-cannot-prove-a-run-so-exit-2"),
    pytest.param("macos", None, False, {"STUB_SUMMARY": '{"unexpected": true}'}, 2,
                 "lacks integer counts", "", True, None,
                 id="macos-summary-without-counts-is-exit-2-not-false-green"),
    pytest.param("macos", "vm\n", True, {"STUB_VM_JSON": '{"total":2,"passed":2,"failed":0,"skipped":0}'}, 0,
                 "executor=vm  skipped=0  executed=2", '"executor": "vm"', False, None,
                 id="macos-vm-pin-runs-the-rig-not-xcodebuild"),
    pytest.param("macos", "vm\n", True, {"STUB_VM_JSON": '{"error":"boot timed out"}', "STUB_VM_STATUS": "2"}, 2,
                 "E2E RIG FAILED: vm-e2e could not run (exit 2)", "", False, None,
                 id="macos-rig-fault-is-exit-2-no-fallback"),
    pytest.param("macos", "vm\n", True, {"STUB_VM_JSON": '{"total":1,"executed":1,"error":"copy failed"}'}, 2,
                 "produced no usable result (exit 0)", "", False, None,
                 id="macos-rig-self-reported-error-is-exit-2"),
    pytest.param("macos", "vm\n", True, {"STUB_VM_JSON": '{"total":2,"passed":0,"failed":0,"skipped":2}'}, 1,
                 "green and empty is not a pass", '"executed": 0', False, None,
                 id="macos-vm-green-and-empty-is-exit-1"),
    pytest.param("macos", "vm\n", True, {"STUB_VM_JSON": '{"total":2,"passed":1,"failed":1,"skipped":0}'}, 1,
                 "executed=2", '"failed": 1', False, None,
                 id="macos-vm-failed-test-is-exit-1"),
    pytest.param("macos", "vm\n", True, {"STUB_VM_JSON": '{"total":2,"passed":2,"failed":0,"skipped":0}',
                                          "STUB_VM_STATUS": "65"}, 65,
                 "despite a clean-looking summary", '"executor": "vm"', False, None,
                 id="macos-vm-clean-summary-keeps-the-rigs-status"),
    pytest.param("macos", "vm\n", False, {"E2E_NONINTERACTIVE": "1"}, 2,
                 "Refusing in a non-interactive session", "", False, None,
                 id="macos-no-rig-non-interactive-refuses"),
    pytest.param("macos", "vm\n", False, {"STUB_SUMMARY": GREEN}, 0,
                 "rig not found on this host", '"executor": "vm→host-fallback"', True, "platform=macOS",
                 id="macos-no-rig-interactive-falls-back-loudly"),
])
def test_the_runner_dispatches_and_exits_as_documented(platform, pin, rig, env, rc, stderr_has,
                                                        stdout_has, xcb_ran, dest):
    """Drives the shipped template against stub tools: the host|vm dispatch, the iOS
    simulator-by-UDID path, the executed==0 rule, and the documented exit codes
    (0 pass, 2 could-not-run, xcodebuild's own status otherwise)."""
    tmpl = (runner_template().replace("<SCHEME>", "X").replace("<PLATFORM>", platform)
            .replace("<TEST_TARGET>", "XUITests"))
    with tempfile.TemporaryDirectory() as d:
        root = Path(d)
        (root / "scripts").mkdir()
        runner = root / "scripts" / "run-uitests.sh"
        runner.write_text(tmpl); runner.chmod(0o755)
        if pin is not None:
            (root / ".gstack").mkdir()
            (root / ".gstack" / "e2e-executor").write_text(pin)
        bins = _stub_bins(root, rig)
        log = root / "log"; log.mkdir()
        # A closed PATH: the developer's own rig (`vm-e2e`) and Xcode must never be
        # reachable from here — the "rig absent" cases exist to prove the fallback.
        full_env = {k: v for k, v in os.environ.items()
                    if k not in ("CI", "GITHUB_ACTIONS", "E2E_NONINTERACTIVE", "PATH")}
        full_env.update({"PATH": f"{bins}:/usr/bin:/bin",
                         "STUB_LOG": str(log), "STUB_SIMS": "", "STUB_SUMMARY": ""})
        full_env.update(env)
        p = subprocess.run(["bash", str(runner)], cwd=root, env=full_env,
                           capture_output=True, text=True, timeout=30)
        assert p.returncode == rc, f"exit {p.returncode}\nstdout:\n{p.stdout}\nstderr:\n{p.stderr}"
        assert stderr_has in p.stderr, p.stderr
        assert stdout_has in p.stdout, p.stdout
        args_file = log / "xcodebuild.args"
        assert args_file.exists() is xcb_ran, "xcodebuild ran" if args_file.exists() else "xcodebuild did not run"
        if dest is not None:
            assert dest in args_file.read_text()
